import { createContext, useContext, useState, useEffect, useCallback } from 'react'

const ThemeContext = createContext(null)

export const LANGUAGES = {
  id: { code: 'id', label: 'Indo', flag: '🇮🇩' },
  en: { code: 'en', label: 'Eng',  flag: '🇺🇸' },
  zh: { code: 'zh', label: '中文',  flag: '🇨🇳' },
  ja: { code: 'ja', label: '日本語', flag: '🇯🇵' },
  ru: { code: 'ru', label: 'Рус',  flag: '🇷🇺' }
}

export const TRANSLATIONS = {
  id: {
    // ── Navigation & metrics ──
    dashboard: 'Dashboard', websites: 'Websites', activity: 'Aktivitas', users: 'Pengguna', notifications: 'Notifikasi', incidents: 'Pusat Insiden',
    online: 'AKTIF', offline: 'MATI', critical: 'KRITIS', warning: 'PERINGATAN', unknown: 'TAK DIKENAL', pending: 'TERTUNDA', total: 'TOTAL', alerts: 'PERINGATAN',
    avgRt: 'RATA-RATA RT',
    // ── Common actions ──
    profile: 'Profil', settings: 'Pengaturan', about: 'Tentang', logout: 'Keluar', save: 'Simpan', cancel: 'Batal', delete: 'Hapus', edit: 'Ubah', back: 'Kembali', show: 'Tampilkan', hide: 'Sembunyikan',
    createUser: 'BUAT USER', addWebsite: 'TAMBAH WEBSITE', clearAll: 'Hapus Semua', markAllRead: 'Tandai Dibaca',
    close: 'Tutup', reset: 'Reset', search: 'Cari', confirm: 'Konfirmasi', apply: 'Terapkan', processing: 'Memproses...', saving: 'Menyimpan...', creating: 'Membuat...', loading: 'Memuat...', sending: 'Mengirim...', remove: 'Hapus',
    // ── TopBar ──
    enterFullScreen: 'Masuk Layar Penuh', exitFullScreen: 'Keluar Layar Penuh', chooseTheme: 'PILIH TEMA', lightMode: 'Mode Terang', darkMode: 'Mode Gelap',
    detail: 'Detail',
    // ── Settings modal ──
    systemSettings: 'Pengaturan Sistem', themeSelection: 'PEMILIHAN TEMA SCI-FI', languageLabel: 'BAHASA', monitoringPreferences: 'PREFERENSI MONITORING',
    notifSound: 'Suara Notifikasi', notifSoundDesc: 'Bunyikan alarm sci-fi saat ada alert baru',
    desktopNotif: 'Notifikasi Desktop', desktopNotifDesc: 'Popup notifikasi OS saat website OFFLINE/CRITICAL (meski tab di-background)',
    autoAck: 'Auto-Acknowledge Pulih', autoAckDesc: 'Tandai notifikasi terbaca otomatis saat website pulih (ONLINE)',
    saveApply: 'Simpan & Terapkan', noDesktopSupport: 'Browser ini tidak mendukung notifikasi desktop.', notifDenied: 'Izin notifikasi ditolak. Aktifkan dari pengaturan situs di browser.',
    // ── About modal ──
    aboutTitle: 'Tentang SPMT Monitoring', systemNameSub: 'NOC Control Panel · Pelindo Multi Terminal',
    aboutPurpose: 'Tujuan', aboutPurposeDesc: 'Memantau ketersediaan dan kinerja seluruh website & layanan digital Pelindo Multi Terminal secara real-time 24/7.',
    aboutHow: 'Cara Kerja', aboutHowDesc: 'Backend Go melakukan pengecekan HTTP/DNS/ICMP/TCP setiap 30-120 detik (sesuai pilihan). Hasilnya dikirim via WebSocket sehingga tampil instan tanpa perlu refresh.',
    aboutSecurity: 'Keamanan', aboutSecurityDesc: 'JWT Token + role-based access: SuperAdmin (akses penuh), Admin (kelola website), Viewer (hanya baca).',
    aboutFeatures: 'Fitur', aboutFeaturesDesc: 'Network Topology (maks. 50 website) · Monitoring Graph (100 pts) · Activity Log · Notifikasi otomatis.',
    sinergiCoreValues: 'Sinergi & Core Values',
    brandPelindoDesc: 'Integrasi layanan pelabuhan nasional.', brandDananDesc: 'Inovasi teknologi digital terintegrasi.', brandBumnDesc: 'Transformasi digital ekonomi nasional.', brandAkhlakDesc: 'Nilai inti budaya kerja yang luhur.',
    // ── Logout ──
    logoutQ: 'Keluar?', logoutConfirm: 'Apakah Anda yakin ingin keluar?',
    // ── Profile modal ──
    customizationProfile: 'Kustomisasi & Profil', uploadPhoto: 'Unggah Foto', roleLabel: 'Peran', generalSettings: 'Pengaturan Umum', securityTab: 'Keamanan',
    personalNotifSettings: 'PENGATURAN NOTIFIKASI PRIBADI', currentEmailAddress: 'ALAMAT EMAIL SAAT INI', required: 'WAJIB', noEmailYet: 'Belum ada email terdaftar',
    changeBtn: 'UBAH', setEmailBtn: 'SET EMAIL', closeBtn: 'TUTUP', updateEmailIdentity: 'PERBARUI IDENTITAS EMAIL',
    confirmCurrentEmail: 'KONFIRMASI EMAIL SAAT INI', typeExistingEmail: 'Ketik email Anda saat ini...', newEmailAddress: 'ALAMAT EMAIL BARU', enterNewEmail: 'Masukkan email baru...', retypeNewEmail: 'KETIK ULANG EMAIL BARU', confirmNewEmail: 'Konfirmasi email baru...',
    confirmIdentityChange: 'KONFIRMASI PERUBAHAN IDENTITAS',
    telegramIntegration: 'INTEGRASI TELEGRAM', optional: 'OPSIONAL', telegramPlaceholder: '@username atau Chat ID...', telegramHelp: 'Digunakan untuk alert cadangan jika email utama tidak terjangkau.', updateBtn: 'PERBARUI', linkBtn: 'HUBUNGKAN',
    testSystemNotif: 'TES NOTIFIKASI SISTEM', testSmtpDesc: 'Verifikasi pengaturan SMTP & Email Anda secara instan', sendTestEmail: 'KIRIM EMAIL TES',
    changeAccountPassword: 'GANTI KATA SANDI AKUN', oldPassword: 'KATA SANDI LAMA', enterCurrentPassword: 'Masukkan kata sandi saat ini', newPassword: 'KATA SANDI BARU', enterNewPassword: 'Masukkan kata sandi baru', confirmNewPassword: 'KONFIRMASI KATA SANDI BARU', repeatNewPassword: 'Ulangi kata sandi baru', updatePassword: 'Perbarui Kata Sandi',
    // ── Network alert ──
    connLost: 'KONEKSI TERPUTUS!', connLostDesc: 'Silakan cek koneksi WiFi atau data seluler di perangkat Anda segera.', connSlow: 'KONEKSI LELET / TIDAK STABIL', connSlowDesc: 'Jaringan Anda sedang lambat. Monitoring mungkin tidak update secara real-time.',
    // ── All notifications panel ──
    allNotifications: 'Semua Notifikasi', statusChangeEventsSession: 'Event perubahan status sesi ini', noNotifSession: 'Tidak ada notifikasi sesi ini',
    // ── Notification bell ──
    notifTitle: 'Notifikasi', markAllReadBtn: 'Tandai semua', unreadLabel: 'belum dibaca', allReadLabel: 'Semua dibaca', noNotifYet: 'Belum ada notifikasi', viewAllNotif: 'Lihat Semua Notifikasi', newBadge: 'BARU',
    statusChange: 'Perubahan Status', rootCause: 'Akar Masalah', ipLabel: 'IP', responseLabel: 'Respon', urlLabel: 'URL', timeLabel: 'Waktu',
    // ── Status panel ──
    liveNodesFeed: 'FEED NODE LANGSUNG', learnStatus: 'Pelajari arti status', searchPlaceholder: 'Cari...', allStatus: 'Semua Status', sortLabel: 'Urutkan', azLabel: 'A - Z', zaLabel: 'Z - A', newestLabel: 'Terbaru', oldestLabel: 'Terlama',
    noMatchingNodes: '// TIDAK ADA NODE COCOK', resetFilters: 'Reset Filter', noServicesConfigured: '// TIDAK ADA LAYANAN DIKONFIGURASI', timeout: 'TIMEOUT',
    // ── Info modal (status guide) ──
    monitoringGuide: 'PANDUAN MONITORING', statusLegendConditions: 'Legenda Status & Kondisi', engineMonitoring: 'ENGINE MONITORING',
    engineDesc: 'Sistem kami melakukan pengecekan kesehatan secara berkala dengan 3 pilihan standar (30s, 60s, atau 120s). Data yang Anda lihat di dashboard ini bersifat Real-Time (Fresh) yang dikirimkan secara langsung melalui WebSocket.',
    legendOnlineCond: 'HTTP 200-399 + RT ≤ 5.000ms', legendOnlineDesc: 'Website sehat, responsif, dan seluruh parameter valid.',
    legendWarningCond: 'Lambat / WAF / Intersepsi', legendWarningDesc: 'Website bisa diakses tetapi mengalami perlambatan atau pembatasan ringan.',
    legendCriticalCond: 'Timeout Parah / Blokir WAF', legendCriticalDesc: 'Sangat sulit diakses, sebagian besar request gagal atau diblokir.',
    legendOfflineCond: 'Down / Timeout Total / TCP Gagal', legendOfflineDesc: 'Website sama sekali tidak dapat dijangkau oleh sistem.',
    // ── Monitoring graph ──
    monitoringStatus: 'STATUS MONITORING', loadingCaps: 'MEMUAT...', liveCaps: 'LANGSUNG', waitingData: 'Menunggu data...', gTotal: 'TOTAL NODE', gUptime: 'UPTIME', gPeak: 'PUNCAK OFFLINE',
    // ── Status distribution ──
    statusDistribution: 'DISTRIBUSI STATUS', servicesLabel: 'layanan', totalLabel: 'Total', noServiceData: 'Belum ada data layanan',
    // ── Monitoring table ──
    monitoringTable: 'TABEL MONITORING', noServicesMatch: 'Tidak ada layanan cocok dengan filter ini', colWebsite: 'Website', colUrl: 'URL', colStatus: 'Status', colHttp: 'HTTP', colResponse: 'Respon', colSsl: 'SSL', colLastCheck: 'Cek Terakhir', validLabel: 'Valid', invalidLabel: 'Invalid',
    // ── Metric detail modal ──
    mdOnline: 'Layanan Online', mdCritical: 'Layanan Kritis', mdOffline: 'Layanan Offline', mdAll: 'Semua Layanan', mdAlerts: 'Peringatan Aktif', mdRtRank: 'Peringkat Waktu Respon', mdSla: 'Ringkasan SLA',
    overallSla: 'SLA Keseluruhan', serviceNameCol: 'NAMA LAYANAN', slaValueCol: 'NILAI SLA', colService: 'Layanan', colResponseTime: 'Waktu Respon', colIssue: 'Masalah', noActiveAlerts: '✅ Tidak ada peringatan aktif — semua sistem beroperasi', noServicesFound: 'Tidak ada layanan ditemukan',
    issueUnreachable: 'Layanan Tak Terjangkau', issueCriticalFail: 'Kegagalan Kritis', issueStability: 'Peringatan Stabilitas',
    mdLegendTitle: 'Keterangan', legStatusTitle: 'Status', legStatusDesc: 'ONLINE: website sehat dan bisa dibuka dengan normal. WARNING: masih bisa dibuka, tapi lambat atau ada gangguan ringan. CRITICAL: sebagian besar gagal atau sangat lambat, hampir tidak bisa dipakai. OFFLINE: sama sekali tidak bisa dijangkau (mati).', legHttpTitle: 'Kode HTTP', legHttpDesc: 'Kode jawaban dari server. 2xx (misal 200): berhasil, halaman terbuka. 3xx (misal 301): dialihkan ke alamat lain. 4xx (misal 404): permintaan ditolak atau halaman tidak ada. 5xx (misal 500): server sedang error. “—” / Timeout: server tidak menjawab sama sekali.', legSslTitle: 'SSL', legSslDesc: '✓ sertifikat valid: koneksi terkunci dan terenkripsi (aman). ✗ tidak valid / kedaluwarsa: sertifikat bermasalah, browser akan menampilkan peringatan ke pengunjung. — tidak diperiksa: website tidak memakai HTTPS, atau belum sempat dicek.', legCheckTitle: 'Cek Terakhir', legCheckDesc: 'Waktu terakhir sistem memeriksa website ini. Makin baru waktunya, makin terbaru pula datanya.',
    legSlaTitle: 'SLA', legSlaDesc: 'Service Level Agreement — persentase waktu layanan tersedia & normal dibanding total waktu pantau. Makin tinggi makin andal.', legSlaValueTitle: 'Nilai per Status', legSlaValueDesc: 'ONLINE 100% · WARNING 90% · CRITICAL 80% · OFFLINE 0%', legSlaOverallTitle: 'SLA Keseluruhan', legSlaOverallDesc: 'Rata-rata SLA dari seluruh layanan yang dipantau.',
    legAvgTitle: 'AVG RT (Rata-rata)', legAvgDesc: 'Average Response Time — rata-rata waktu respon seluruh layanan; ini angka pada kartu AVG RT.', legRtTitle: 'Waktu Respon', legRtDesc: 'Lama tiap layanan membalas permintaan — makin kecil makin cepat.', legRtColorTitle: 'Kode Warna', legRtColorDesc: 'Hijau < 3000ms · Kuning 3000–10000ms · Merah > 10000ms', legRtRankTitle: 'Peringkat', legRtRankDesc: 'Diurutkan dari respon paling lambat; 3 teratas disorot.',
    // ── Service detail modal ──
    tabOverview: 'RINGKASAN', tabPerformance: 'KINERJA', tabTimeline: 'LINIMASA', tabHistory: 'RIWAYAT',
    conditionWebsite: 'KONDISI WEBSITE', botChrome: 'BOT CHROME', copyScreenshot: 'Salin Screenshot', copied: 'Tersalin!',
    cardServiceHealth: 'KESEHATAN LAYANAN', cardConnectivity: 'KONEKTIVITAS', cardSecurity: 'KEAMANAN', cardInfrastructure: 'INFRASTRUKTUR',
    rowStatus: 'Status', rowHttpCode: 'Kode HTTP', rowResponseTime: 'Waktu Respon', rowTtfb: 'TTFB', rowLastCheck: 'Cek Terakhir', rowIcmpPing: 'Ping ICMP', rowDnsStatus: 'Status DNS', rowDnsLookup: 'Waktu Lookup DNS', rowIpAddress: 'Alamat IP', rowSslStatus: 'Status SSL', rowExpiration: 'Tanggal Kedaluwarsa', rowRemainingDays: 'Sisa Hari', rowServer: 'Server', rowBotDetector: 'Pendeteksi Bot',
    valFailed: 'Gagal', valResolved: 'Terurai', valValid: 'Valid', valInvalid: 'Invalid', valToday: 'Hari Ini', valExpired: 'Kedaluwarsa', valDays: 'Hari', valUnknown: 'Tidak Diketahui',
    tlLoading: 'Memuat linimasa...', tlNoEvents: 'Belum ada event perubahan status.', tlEventsNewest: 'event perubahan status — terbaru dahulu', tlDurationBar: 'BAR DURASI STATUS', tlOldest: 'Terlama', tlNewest: 'Terbaru', tlDuration: 'Durasi', tlOngoing: 'berlangsung',
    perfAvgResponse: 'Rata-rata Respon', perfSlowest: 'Terlambat', perfFastest: 'Tercepat', perfResponseLast: 'WAKTU RESPON — TERAKHIR', perfChecks: 'PENGECEKAN', perfTotalChecks: 'Total Pengecekan (sampel)', perfSuccessfulChecks: 'Pengecekan Berhasil', perfSampleUptime: 'Uptime Sampel', visitWebsite: 'KUNJUNGI WEBSITE', noHistory: 'Tidak ada riwayat', noAlertsService: '✅ Tidak ada peringatan untuk layanan ini', colHealth: 'Health',
    // ── Websites page ──
    websiteManagement: 'Manajemen Website', websitesConfigured: 'website dikonfigurasi', searchWebsiteUrl: 'Cari website atau URL...', recommendations: 'REKOMENDASI',
    sortNameAz: 'Nama (A - Z)', sortNameZa: 'Nama (Z - A)', sortNewestCreated: 'Terbaru Dibuat', sortOldestCreated: 'Terlama Dibuat',
    addWebsiteBtn: '+ Tambah Website', limitReached: 'Batas Tercapai', limitReachedTitle: 'Batas 100 website tercapai', addNewWebsiteTitle: 'Tambah website baru',
    noWebsitesConfigured: 'Belum ada website dikonfigurasi.', clickAddWebsite: 'Klik "Tambah Website" untuk mulai.', noWebsitesMatch: 'Tidak ada website cocok dengan pencarian atau filter saat ini.',
    thWebsite: 'WEBSITE', thUrlEndpoint: 'URL / ENDPOINT', thInterval: 'INTERVAL', thStatus: 'STATUS', thHealth: 'HEALTH', thLatency: 'LATENSI', thHttp: 'HTTP', thSsl: 'SSL', thNetLatencies: 'LATENSI JARINGAN', thActions: 'AKSI',
    editBtn: 'Ubah', deleteBtn: 'Hapus', editWebsiteTitle: 'Ubah Website', addWebsiteModalTitle: 'Tambah Website', confirmDeleteTitle: 'Konfirmasi Hapus',
    fieldName: 'NAMA *', fieldNamePh: 'Website Saya', fieldUrl: 'URL *', fieldDescription: 'DESKRIPSI', fieldDescriptionPh: 'Deskripsi opsional', fieldInterval: 'INTERVAL MONITORING',
    interval30: '30 Detik (Cepat)', interval60: '60 Detik (Direkomendasikan)', interval120: '120 Detik (Normal)', secondsCurrent: 'Detik (Saat Ini)',
    takeScreenshot: 'AMBIL SCREENSHOT HALAMAN (SIMPAN FOTO)', saveBtn: 'Simpan', failedToSave: 'Gagal menyimpan',
    deleteConfirmPrefix: 'Hapus', deleteConfirmSuffix: '? Ini juga akan menghapus permanen seluruh log monitoring dari database.',
    selectMode: 'Mode Pilih', selectAllTitle: 'Pilih semua di halaman ini', selectedSuffix: 'dipilih', clearSelectionBtn: 'Batal Pilih', deleteSelectedBtn: 'Hapus Terpilih', bulkDeleteTitle: 'Konfirmasi Hapus Massal', bulkDeleteUnit: 'website terpilih',
    deleteAllBtn: 'Hapus Semua', bulkDeleteFailed: 'Gagal menghapus website. Silakan coba lagi.', bulkDeleteAllWarning: 'Anda akan menghapus SEMUA website beserta seluruh log & riwayat monitoringnya secara permanen. Tindakan ini tidak dapat dibatalkan.', bulkConfirmTypePrefix: 'Ketik', bulkConfirmTypeSuffix: 'untuk melanjutkan.', bulkDeleteAllKeyword: 'HAPUS SEMUA',
    exp: 'Exp', ipLabelShort: 'IP',
    // ── Activity log ──
    activityLogTitle: 'Log Aktivitas', completeHistory: 'Riwayat lengkap', eventsLabel: 'event', noEventsFound: 'Tidak ada event ditemukan.',
    colTransition: 'Transisi', colNewStatus: 'Status Baru', colTime: 'Waktu',
    // ── Users page ──
    userManagement: 'Manajemen Pengguna', usersLabel: 'pengguna', adminsUsed: 'admin terpakai', createUserBtn: '+ BUAT USER', adminSlots: 'SLOT ADMIN',
    pendingApprovals: 'Registrasi Menunggu Konfirmasi', pendingApprovalsSub: 'User baru menunggu persetujuan Anda sebelum dapat login.',
    approveBtn: 'Izinkan', rejectBtn: 'Tolak', approveTooltip: 'Izinkan registrasi', rejectTooltip: 'Tolak registrasi',
    approveUserTitle: 'Izinkan Registrasi', approveUserConfirmPrefix: 'Apakah user', approveUserConfirmSuffix: 'ini diizinkan membuat akun baru?',
    rejectUserTitle: 'Tolak Registrasi', rejectUserConfirmPrefix: 'Anda menolak user', rejectUserConfirmSuffix: 'ini sebagai user baru. Registrasinya akan dihapus.',
    userApprovedMsg: 'User disetujui — sekarang sudah bisa login', userRejectedMsg: 'Registrasi ditolak',
    thUsername: 'USERNAME', thRole: 'PERAN', thCreatedAt: 'DIBUAT PADA', noUsersFound: 'Tidak ada pengguna ditemukan.', protectedLabel: 'Terlindungi', currentUserLabel: 'Pengguna saat ini', youLabel: 'Anda',
    promoteBtn: '↑ Naikkan', demoteBtn: '↓ Turunkan', maxAdminsReached: 'Maks 3 admin tercapai', promoteToAdmin: 'Naikkan ke Admin',
    deleteUserTitle: 'Hapus Pengguna', deleteUserConfirmPrefix: 'Hapus', cannotBeUndone: '? Tindakan ini tidak bisa dibatalkan.', createNewUser: 'Buat Pengguna Baru',
    fieldPassword: 'KATA SANDI', passwordMinPh: 'kata sandi (min 6 karakter)', roleViewer: 'Viewer', roleAdmin: 'Admin', roleAdminPelindo: 'Admin Pelindo', fieldEmail: 'EMAIL *', fieldTelegramOpt: 'TELEGRAM ID (Opsional)', createUserSubmit: 'Buat Pengguna',
    // ── Network topology ──
    refresh: 'REFRESH', refreshing: 'MEMUAT ULANG...', connecting: 'MENGHUBUNGKAN', allMonitoredNodes: 'Semua Node Dipantau', searchNodeUrl: 'Cari nama node atau URL...',
    thEndpointName: 'NAMA ENDPOINT', thUrl: 'URL', noWebsitesMonitored: 'Tidak ada website dipantau', addWebsitesToBegin: 'Tambahkan website untuk mulai monitoring',
    cpuUsage: 'PENGGUNAAN CPU', ramUsage: 'PENGGUNAAN RAM', networkConnection: 'KONEKSI JARINGAN', netType: 'TIPE', netName: 'NAMA JARINGAN', endpointIpAddress: 'ENDPOINT & ALAMAT IP', httpCodeLabel: 'KODE HTTP', sslStatusLabel: 'STATUS SSL', lastCheckLabel: 'CEK TERAKHIR', failedRecheck: 'Gagal memicu pengecekan ulang',
    networkTopologyTitle: 'TOPOLOGI JARINGAN', nodesLabel: 'node', moreLabel: 'LAGI', listLabel: 'Daftar', mapLabel: 'Peta', showingAll: 'Menampilkan semua', endpointsLabel: 'endpoint', noNodesMatch: 'Tidak ada node cocok dengan pencarian atau filter terpilih.', highLoadClick: '⚠️ BEBAN TINGGI — Klik untuk detail',
    // ── Login page ──
    // ── Server detail modal ──
    srvResourceUsage: 'PENGGUNAAN SUMBER DAYA', srvWorkerRuntime: 'WORKER & RUNTIME', srvNetworkInfo: 'INFORMASI JARINGAN', srvAnalysis: 'ANALISIS & REKOMENDASI', srvActiveWorkers: 'WORKER AKTIF', srvQueueSize: 'UKURAN ANTRIAN', srvGoroutines: 'GOROUTINE', srvWsConn: 'KONEKSI WS', srvConnType: 'Tipe Koneksi', srvNetName: 'Nama Jaringan', srvInterface: 'Antarmuka', srvGateway: 'Gateway', srvDnsResolver: 'DNS Resolver', srvLinkSpeed: 'Kecepatan Jaringan', srvDownload: 'Unduh', srvUpload: 'Unggah', srvLoading: 'Memuat data server…', srvAutoRefresh: 'Refresh otomatis setiap 4 detik · tekan Esc untuk tutup', srvLocalSystem: 'Sistem Lokal', srvUpdated: 'Diperbarui', srvNormal: 'NORMAL', srvExceeds: 'Melebihi ambang',
    createAccount: 'Buat Akun', welcome: 'Selamat Datang', signUpMonitor: 'Daftar untuk memantau layanan', signInAccess: 'Masuk untuk mengakses dashboard monitoring',
    usernamePh: 'Username', emailReqPh: 'Email *', telegramOptPh: 'Telegram ID (opsional)', passwordPh: 'Password', register: 'DAFTAR', signIn: 'MASUK',
    alreadyHaveAccount: 'Sudah punya akun? ', needAccount: 'Butuh akun? ', signInLink: 'Masuk', registerHere: 'Daftar di sini', completeCaptcha: 'Mohon selesaikan CAPTCHA', regSuccess: 'Registrasi berhasil! Akun Anda menunggu persetujuan admin sebelum dapat login.', regFailed: 'Registrasi gagal.', loginFailed: 'Login gagal. Periksa kredensial.', loginSuccess: 'Berhasil Masuk', rememberMe: 'Ingat saya', telegramPhonePh: 'Nomor telepon Telegram (mis. 0812xxxxxxx)',
  },
  en: {
    dashboard: 'Dashboard', websites: 'Websites', activity: 'Activity', users: 'Users', notifications: 'Notifications', incidents: 'Incident Center',
    online: 'ONLINE', offline: 'OFFLINE', critical: 'CRITICAL', warning: 'WARNING', unknown: 'UNKNOWN', pending: 'PENDING', total: 'TOTAL', alerts: 'ALERTS',
    avgRt: 'AVG RT',
    profile: 'Profile', settings: 'Settings', about: 'About', logout: 'Logout', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', back: 'Back', show: 'Show', hide: 'Hide',
    createUser: 'CREATE USER', addWebsite: 'ADD WEBSITE', clearAll: 'Clear All', markAllRead: 'Mark All Read',
    close: 'Close', reset: 'Reset', search: 'Search', confirm: 'Confirm', apply: 'Apply', processing: 'Processing...', saving: 'Saving...', creating: 'Creating...', loading: 'Loading...', sending: 'Sending...', remove: 'Remove',
    enterFullScreen: 'Enter Full Screen', exitFullScreen: 'Exit Full Screen', chooseTheme: 'CHOOSE THEME', lightMode: 'Light Mode', darkMode: 'Dark Mode',
    detail: 'Detail',
    systemSettings: 'System Settings', themeSelection: 'SCI-FI THEME SELECTION', languageLabel: 'LANGUAGE', monitoringPreferences: 'MONITORING PREFERENCES',
    notifSound: 'Notification Sound', notifSoundDesc: 'Play sci-fi alarm when a new alert arrives',
    desktopNotif: 'Desktop Notification', desktopNotifDesc: 'OS notification popup when a website is OFFLINE/CRITICAL (even if tab is in background)',
    autoAck: 'Auto-Acknowledge Resolved', autoAckDesc: 'Automatically mark notifications read when a website recovers (ONLINE)',
    saveApply: 'Save & Apply', noDesktopSupport: 'This browser does not support desktop notifications.', notifDenied: 'Notification permission denied. Enable it from the site settings in your browser.',
    aboutTitle: 'About SPMT Monitoring', systemNameSub: 'NOC Control Panel · Pelindo Multi Terminal',
    aboutPurpose: 'Purpose', aboutPurposeDesc: 'Monitor the availability and performance of all Pelindo Multi Terminal websites & digital services in real-time, 24/7.',
    aboutHow: 'How It Works', aboutHowDesc: 'The Go backend runs HTTP/DNS/ICMP/TCP checks every 30-120 seconds (configurable). Results are pushed via WebSocket so they appear instantly without a refresh.',
    aboutSecurity: 'Security', aboutSecurityDesc: 'JWT Token + role-based access: SuperAdmin (full access), Admin (manage websites), Viewer (read only).',
    aboutFeatures: 'Features', aboutFeaturesDesc: 'Network Topology (max 50 websites) · Monitoring Graph (100 pts) · Activity Log · Automatic notifications.',
    sinergiCoreValues: 'Synergy & Core Values',
    brandPelindoDesc: 'Integration of national port services.', brandDananDesc: 'Integrated digital technology innovation.', brandBumnDesc: 'National economic digital transformation.', brandAkhlakDesc: 'Core values of a noble work culture.',
    logoutQ: 'Logout?', logoutConfirm: 'Are you sure you want to logout?',
    customizationProfile: 'Customization & Profile', uploadPhoto: 'Upload Photo', roleLabel: 'Role', generalSettings: 'General Settings', securityTab: 'Security',
    personalNotifSettings: 'PERSONAL NOTIFICATION SETTINGS', currentEmailAddress: 'CURRENT EMAIL ADDRESS', required: 'REQUIRED', noEmailYet: 'No email registered yet',
    changeBtn: 'CHANGE', setEmailBtn: 'SET EMAIL', closeBtn: 'CLOSE', updateEmailIdentity: 'UPDATE EMAIL IDENTITY',
    confirmCurrentEmail: 'CONFIRM CURRENT EMAIL', typeExistingEmail: 'Type your existing email...', newEmailAddress: 'NEW EMAIL ADDRESS', enterNewEmail: 'Enter new email...', retypeNewEmail: 'RE-TYPE NEW EMAIL', confirmNewEmail: 'Confirm new email...',
    confirmIdentityChange: 'CONFIRM IDENTITY CHANGE',
    telegramIntegration: 'TELEGRAM INTEGRATION', optional: 'OPTIONAL', telegramPlaceholder: '@username or Chat ID...', telegramHelp: 'Used for backup alerts if primary email is unreachable.', updateBtn: 'UPDATE', linkBtn: 'LINK',
    testSystemNotif: 'TEST SYSTEM NOTIFICATIONS', testSmtpDesc: 'Verify your SMTP & Email settings instantly', sendTestEmail: 'SEND TEST EMAIL',
    changeAccountPassword: 'CHANGE ACCOUNT PASSWORD', oldPassword: 'OLD PASSWORD', enterCurrentPassword: 'Enter current password', newPassword: 'NEW PASSWORD', enterNewPassword: 'Enter new password', confirmNewPassword: 'CONFIRM NEW PASSWORD', repeatNewPassword: 'Repeat new password', updatePassword: 'Update Password',
    connLost: 'CONNECTION LOST!', connLostDesc: 'Please check the WiFi or mobile data connection on your device immediately.', connSlow: 'SLOW / UNSTABLE CONNECTION', connSlowDesc: 'Your network is slow. Monitoring may not update in real-time.',
    allNotifications: 'All Notifications', statusChangeEventsSession: 'Status change events this session', noNotifSession: 'No notifications this session',
    notifTitle: 'Notifications', markAllReadBtn: 'Mark all read', unreadLabel: 'unread', allReadLabel: 'All read', noNotifYet: 'No notifications yet', viewAllNotif: 'View All Notifications', newBadge: 'NEW',
    statusChange: 'Status Change', rootCause: 'Root Cause', ipLabel: 'IP', responseLabel: 'Response', urlLabel: 'URL', timeLabel: 'Time',
    liveNodesFeed: 'LIVE NODES FEED', learnStatus: 'Learn about status meanings', searchPlaceholder: 'Search...', allStatus: 'All Status', sortLabel: 'Sort', azLabel: 'A - Z', zaLabel: 'Z - A', newestLabel: 'Newest', oldestLabel: 'Oldest',
    noMatchingNodes: '// NO MATCHING NODES FOUND', resetFilters: 'Reset Filters', noServicesConfigured: '// NO SERVICES CONFIGURED', timeout: 'TIMEOUT',
    monitoringGuide: 'MONITORING GUIDE', statusLegendConditions: 'Status Legend & Conditions', engineMonitoring: 'MONITORING ENGINE',
    engineDesc: 'Our system runs periodic health checks with 3 standard options (30s, 60s, or 120s). The data you see on this dashboard is Real-Time (Fresh), pushed live over WebSocket.',
    legendOnlineCond: 'HTTP 200-399 + RT ≤ 5,000ms', legendOnlineDesc: 'Website is healthy, responsive, and all parameters are valid.',
    legendWarningCond: 'Slow / WAF / Intercept', legendWarningDesc: 'Website is reachable but experiencing slowdowns or minor restrictions.',
    legendCriticalCond: 'Severe Timeout / WAF Block', legendCriticalDesc: 'Very hard to reach, most requests fail or are blocked.',
    legendOfflineCond: 'Down / Total Timeout / TCP Fail', legendOfflineDesc: 'Website is completely unreachable by the system.',
    monitoringStatus: 'MONITORING STATUS', loadingCaps: 'LOADING...', liveCaps: 'LIVE', waitingData: 'Waiting for data...', gTotal: 'TOTAL NODES', gUptime: 'UPTIME', gPeak: 'PEAK OFFLINE',
    statusDistribution: 'STATUS DISTRIBUTION', servicesLabel: 'services', totalLabel: 'Total', noServiceData: 'No service data yet',
    monitoringTable: 'MONITORING TABLE', noServicesMatch: 'No services match this filter', colWebsite: 'Website', colUrl: 'URL', colStatus: 'Status', colHttp: 'HTTP', colResponse: 'Response', colSsl: 'SSL', colLastCheck: 'Last Check', validLabel: 'Valid', invalidLabel: 'Invalid',
    mdOnline: 'Online Services', mdCritical: 'Critical Services', mdOffline: 'Offline Services', mdAll: 'All Services', mdAlerts: 'Active Alerts', mdRtRank: 'Response Time Ranking', mdSla: 'SLA Overview',
    overallSla: 'Overall SLA', serviceNameCol: 'SERVICE NAME', slaValueCol: 'SLA VALUE', colService: 'Service', colResponseTime: 'Response Time', colIssue: 'Issue', noActiveAlerts: '✅ No active alerts — all systems operational', noServicesFound: 'No services found',
    issueUnreachable: 'Service Unreachable', issueCriticalFail: 'Critical Failure', issueStability: 'Stability Warning',
    mdLegendTitle: 'Legend', legStatusTitle: 'Status', legStatusDesc: 'ONLINE: the site is healthy and opens normally. WARNING: still reachable, but slow or slightly degraded. CRITICAL: mostly failing or very slow, barely usable. OFFLINE: completely unreachable (down).', legHttpTitle: 'HTTP Code', legHttpDesc: 'The reply code from the server. 2xx (e.g. 200): success, the page opens. 3xx (e.g. 301): redirected to another address. 4xx (e.g. 404): the request was refused or the page is missing. 5xx (e.g. 500): the server itself is failing. “—” / Timeout: the server gave no reply at all.', legSslTitle: 'SSL', legSslDesc: '✓ valid certificate: the connection is locked and encrypted. ✗ invalid / expired: the certificate has a problem and the browser will warn visitors. — not checked: the site has no HTTPS, or it has not been checked yet.', legCheckTitle: 'Last Check', legCheckDesc: 'The last time the system checked this website. The more recent it is, the more up to date the data.',
    legSlaTitle: 'SLA', legSlaDesc: 'Service Level Agreement — percentage of time the service was available & healthy versus total monitored time. Higher is more reliable.', legSlaValueTitle: 'Value per Status', legSlaValueDesc: 'ONLINE 100% · WARNING 90% · CRITICAL 80% · OFFLINE 0%', legSlaOverallTitle: 'Overall SLA', legSlaOverallDesc: 'Average SLA across all monitored services.',
    legAvgTitle: 'AVG RT (Average)', legAvgDesc: 'Average Response Time — the mean response time across all services; this is the number on the AVG RT card.', legRtTitle: 'Response Time', legRtDesc: 'How long each service takes to reply — lower is faster.', legRtColorTitle: 'Color Code', legRtColorDesc: 'Green < 3000ms · Amber 3000–10000ms · Red > 10000ms', legRtRankTitle: 'Ranking', legRtRankDesc: 'Sorted by slowest response; top 3 are highlighted.',
    tabOverview: 'OVERVIEW', tabPerformance: 'PERFORMANCE', tabTimeline: 'TIMELINE', tabHistory: 'HISTORY',
    conditionWebsite: 'WEBSITE CONDITION', botChrome: 'CHROME BOT', copyScreenshot: 'Copy Screenshot', copied: 'Copied!',
    cardServiceHealth: 'SERVICE HEALTH', cardConnectivity: 'CONNECTIVITY', cardSecurity: 'SECURITY', cardInfrastructure: 'INFRASTRUCTURE',
    rowStatus: 'Status', rowHttpCode: 'HTTP Code', rowResponseTime: 'Response Time', rowTtfb: 'TTFB', rowLastCheck: 'Last Check', rowIcmpPing: 'ICMP Ping', rowDnsStatus: 'DNS Status', rowDnsLookup: 'DNS Lookup Time', rowIpAddress: 'IP Address', rowSslStatus: 'SSL Status', rowExpiration: 'Expiration Date', rowRemainingDays: 'Remaining Days', rowServer: 'Server', rowBotDetector: 'Bot Detector',
    valFailed: 'Failed', valResolved: 'Resolved', valValid: 'Valid', valInvalid: 'Invalid', valToday: 'Today', valExpired: 'Expired', valDays: 'Days', valUnknown: 'Unknown',
    tlLoading: 'Loading timeline...', tlNoEvents: 'No status change events recorded yet.', tlEventsNewest: 'status change events — newest first', tlDurationBar: 'STATUS DURATION BAR', tlOldest: 'Oldest', tlNewest: 'Newest', tlDuration: 'Duration', tlOngoing: 'ongoing',
    perfAvgResponse: 'Avg Response', perfSlowest: 'Slowest', perfFastest: 'Fastest', perfResponseLast: 'RESPONSE TIME — LAST', perfChecks: 'CHECKS', perfTotalChecks: 'Total Checks (sample)', perfSuccessfulChecks: 'Successful Checks', perfSampleUptime: 'Sample Uptime', visitWebsite: 'VISIT WEBSITE', noHistory: 'No history', noAlertsService: '✅ No alerts for this service', colHealth: 'Health',
    websiteManagement: 'Website Management', websitesConfigured: 'websites configured', searchWebsiteUrl: 'Search website or URL...', recommendations: 'RECOMMENDATIONS',
    sortNameAz: 'Name (A - Z)', sortNameZa: 'Name (Z - A)', sortNewestCreated: 'Newest Created', sortOldestCreated: 'Oldest Created',
    addWebsiteBtn: '+ Add Website', limitReached: 'Limit Reached', limitReachedTitle: 'Limit 100 websites reached', addNewWebsiteTitle: 'Add new website',
    noWebsitesConfigured: 'No websites configured.', clickAddWebsite: 'Click "Add Website" to begin.', noWebsitesMatch: 'No websites match the current search or filters.',
    thWebsite: 'WEBSITE', thUrlEndpoint: 'URL / ENDPOINT', thInterval: 'INTERVAL', thStatus: 'STATUS', thHealth: 'HEALTH', thLatency: 'LATENCY', thHttp: 'HTTP', thSsl: 'SSL', thNetLatencies: 'NET LATENCIES', thActions: 'ACTIONS',
    editBtn: 'Edit', deleteBtn: 'Delete', editWebsiteTitle: 'Edit Website', addWebsiteModalTitle: 'Add Website', confirmDeleteTitle: 'Confirm Delete',
    fieldName: 'NAME *', fieldNamePh: 'My Website', fieldUrl: 'URL *', fieldDescription: 'DESCRIPTION', fieldDescriptionPh: 'Optional description', fieldInterval: 'MONITORING INTERVAL',
    interval30: '30 Seconds (Fast)', interval60: '60 Seconds (Recommended)', interval120: '120 Seconds (Normal)', secondsCurrent: 'Seconds (Current)',
    takeScreenshot: 'CAPTURE PAGE SCREENSHOT (SAVE PHOTO)', saveBtn: 'Save', failedToSave: 'Failed to save',
    deleteConfirmPrefix: 'Delete', deleteConfirmSuffix: '? This will also permanently remove all monitoring logs from the database.',
    selectMode: 'Selection Mode', selectAllTitle: 'Select all on this page', selectedSuffix: 'selected', clearSelectionBtn: 'Clear', deleteSelectedBtn: 'Delete Selected', bulkDeleteTitle: 'Confirm Bulk Delete', bulkDeleteUnit: 'selected websites',
    deleteAllBtn: 'Delete All', bulkDeleteFailed: 'Failed to delete websites. Please try again.', bulkDeleteAllWarning: 'You are about to permanently delete ALL websites along with all their monitoring logs & history. This action cannot be undone.', bulkConfirmTypePrefix: 'Type', bulkConfirmTypeSuffix: 'to continue.', bulkDeleteAllKeyword: 'DELETE ALL',
    exp: 'Exp', ipLabelShort: 'IP',
    activityLogTitle: 'Activity Log', completeHistory: 'Complete history', eventsLabel: 'events', noEventsFound: 'No events found.',
    colTransition: 'Transition', colNewStatus: 'New Status', colTime: 'Time',
    userManagement: 'User Management', usersLabel: 'users', adminsUsed: 'admins used', createUserBtn: '+ CREATE USER', adminSlots: 'ADMIN SLOTS',
    pendingApprovals: 'Pending Registrations', pendingApprovalsSub: 'New users awaiting your confirmation before they can log in.',
    approveBtn: 'Approve', rejectBtn: 'Reject', approveTooltip: 'Approve registration', rejectTooltip: 'Reject registration',
    approveUserTitle: 'Approve Registration', approveUserConfirmPrefix: 'Allow user', approveUserConfirmSuffix: 'to create a new account?',
    rejectUserTitle: 'Reject Registration', rejectUserConfirmPrefix: 'You are rejecting', rejectUserConfirmSuffix: 'as a new user. Their registration will be removed.',
    userApprovedMsg: 'User approved — they can now log in', userRejectedMsg: 'Registration rejected',
    thUsername: 'USERNAME', thRole: 'ROLE', thCreatedAt: 'CREATED AT', noUsersFound: 'No users found.', protectedLabel: 'Protected', currentUserLabel: 'Current user', youLabel: 'You',
    promoteBtn: '↑ Promote', demoteBtn: '↓ Demote', maxAdminsReached: 'Max 3 admins reached', promoteToAdmin: 'Promote to Admin',
    deleteUserTitle: 'Delete User', deleteUserConfirmPrefix: 'Delete', cannotBeUndone: '? This cannot be undone.', createNewUser: 'Create New User',
    fieldPassword: 'PASSWORD', passwordMinPh: 'password (min 6 chars)', roleViewer: 'Viewer', roleAdmin: 'Admin', roleAdminPelindo: 'Admin Pelindo', fieldEmail: 'EMAIL *', fieldTelegramOpt: 'TELEGRAM ID (Optional)', createUserSubmit: 'Create User',
    refresh: 'REFRESH', refreshing: 'REFRESHING...', connecting: 'CONNECTING', allMonitoredNodes: 'All Monitored Nodes', searchNodeUrl: 'Search node name or URL...',
    thEndpointName: 'ENDPOINT NAME', thUrl: 'URL', noWebsitesMonitored: 'No websites monitored', addWebsitesToBegin: 'Add websites to begin monitoring',
    cpuUsage: 'CPU USAGE', ramUsage: 'RAM USAGE', networkConnection: 'NETWORK CONNECTION', netType: 'TYPE', netName: 'NETWORK NAME', endpointIpAddress: 'ENDPOINT & IP ADDRESS', httpCodeLabel: 'HTTP CODE', sslStatusLabel: 'SSL STATUS', lastCheckLabel: 'LAST CHECK', failedRecheck: 'Failed to trigger recheck',
    networkTopologyTitle: 'NETWORK TOPOLOGY', nodesLabel: 'nodes', moreLabel: 'MORE', listLabel: 'List', mapLabel: 'Map', showingAll: 'Showing all', endpointsLabel: 'endpoints', noNodesMatch: 'No nodes match the selected search or filters.', highLoadClick: '⚠️ HIGH LOAD — Click for details',
    srvResourceUsage: 'RESOURCE USAGE', srvWorkerRuntime: 'WORKER & RUNTIME', srvNetworkInfo: 'NETWORK INFORMATION', srvAnalysis: 'ANALYSIS & RECOMMENDATIONS', srvActiveWorkers: 'ACTIVE WORKERS', srvQueueSize: 'QUEUE SIZE', srvGoroutines: 'GOROUTINES', srvWsConn: 'WS CONNECTIONS', srvConnType: 'Connection Type', srvNetName: 'Network Name', srvInterface: 'Interface', srvGateway: 'Gateway', srvDnsResolver: 'DNS Resolver', srvLinkSpeed: 'Link Speed', srvDownload: 'Download', srvUpload: 'Upload', srvLoading: 'Loading server data…', srvAutoRefresh: 'Auto-refresh every 4 seconds · press Esc to close', srvLocalSystem: 'Local System', srvUpdated: 'Updated', srvNormal: 'NORMAL', srvExceeds: 'Exceeds threshold',
    createAccount: 'Create Account', welcome: 'Welcome', signUpMonitor: 'Sign up to monitor services', signInAccess: 'Sign in to access the monitoring dashboard',
    usernamePh: 'Username', emailReqPh: 'Email *', telegramOptPh: 'Telegram ID (optional)', passwordPh: 'Password', register: 'REGISTER', signIn: 'SIGN IN',
    alreadyHaveAccount: 'Already have an account? ', needAccount: 'Need an account? ', signInLink: 'Sign in', registerHere: 'Register here', completeCaptcha: 'Please complete the CAPTCHA', regSuccess: 'Registration successful! Your account is awaiting admin approval before you can sign in.', regFailed: 'Registration failed.', loginFailed: 'Login failed. Check credentials.', loginSuccess: 'Login Successfully', rememberMe: 'Remember me', telegramPhonePh: 'Telegram phone number (e.g. 0812xxxxxxx)',
  },
  zh: {
    dashboard: '仪表板', websites: '网站', activity: '活动', users: '用户', notifications: '通知', incidents: '事件中心',
    online: '在线', offline: '离线', critical: '严重', warning: '警告', unknown: '未知', pending: '待定', total: '总计', alerts: '警报',
    avgRt: '平均响应',
    profile: '个人资料', settings: '设置', about: '关于', logout: '登出', save: '保存', cancel: '取消', delete: '删除', edit: '编辑', back: '返回', show: '显示', hide: '隐藏',
    createUser: '创建用户', addWebsite: '添加网站', clearAll: '清除全部', markAllRead: '全部已读',
    close: '关闭', reset: '重置', search: '搜索', confirm: '确认', apply: '应用', processing: '处理中...', saving: '保存中...', creating: '创建中...', loading: '加载中...', sending: '发送中...', remove: '移除',
    enterFullScreen: '进入全屏', exitFullScreen: '退出全屏', chooseTheme: '选择主题', lightMode: '浅色模式', darkMode: '深色模式',
    detail: '详情',
    systemSettings: '系统设置', themeSelection: '科幻主题选择', languageLabel: '语言', monitoringPreferences: '监控偏好',
    notifSound: '通知声音', notifSoundDesc: '有新警报时播放科幻警报声',
    desktopNotif: '桌面通知', desktopNotifDesc: '当网站离线/严重时弹出系统通知（即使标签页在后台）',
    autoAck: '自动确认恢复', autoAckDesc: '当网站恢复（在线）时自动将通知标记为已读',
    saveApply: '保存并应用', noDesktopSupport: '此浏览器不支持桌面通知。', notifDenied: '通知权限被拒绝。请在浏览器的站点设置中启用。',
    aboutTitle: '关于 SPMT 监控', systemNameSub: 'NOC 控制面板 · Pelindo Multi Terminal',
    aboutPurpose: '目的', aboutPurposeDesc: '全天候 24/7 实时监控 Pelindo Multi Terminal 所有网站与数字服务的可用性和性能。',
    aboutHow: '工作原理', aboutHowDesc: 'Go 后端每 30-120 秒（可配置）执行 HTTP/DNS/ICMP/TCP 检查。结果通过 WebSocket 推送，无需刷新即可即时显示。',
    aboutSecurity: '安全', aboutSecurityDesc: 'JWT 令牌 + 基于角色的访问：超级管理员（完全访问）、管理员（管理网站）、查看者（只读）。',
    aboutFeatures: '功能', aboutFeaturesDesc: '网络拓扑（最多 50 个网站）· 监控图表（100 点）· 活动日志 · 自动通知。',
    sinergiCoreValues: '协同与核心价值',
    brandPelindoDesc: '整合国家港口服务。', brandDananDesc: '集成数字技术创新。', brandBumnDesc: '国家经济数字化转型。', brandAkhlakDesc: '崇高工作文化的核心价值。',
    logoutQ: '登出？', logoutConfirm: '确定要登出吗？',
    customizationProfile: '自定义与个人资料', uploadPhoto: '上传照片', roleLabel: '角色', generalSettings: '常规设置', securityTab: '安全',
    personalNotifSettings: '个人通知设置', currentEmailAddress: '当前邮箱地址', required: '必填', noEmailYet: '尚未注册邮箱',
    changeBtn: '更改', setEmailBtn: '设置邮箱', closeBtn: '关闭', updateEmailIdentity: '更新邮箱身份',
    confirmCurrentEmail: '确认当前邮箱', typeExistingEmail: '输入您现有的邮箱...', newEmailAddress: '新邮箱地址', enterNewEmail: '输入新邮箱...', retypeNewEmail: '重新输入新邮箱', confirmNewEmail: '确认新邮箱...',
    confirmIdentityChange: '确认身份变更',
    telegramIntegration: 'TELEGRAM 集成', optional: '可选', telegramPlaceholder: '@用户名 或 Chat ID...', telegramHelp: '当主邮箱无法送达时用于备用警报。', updateBtn: '更新', linkBtn: '关联',
    testSystemNotif: '测试系统通知', testSmtpDesc: '即时验证您的 SMTP 与邮箱设置', sendTestEmail: '发送测试邮件',
    changeAccountPassword: '更改账户密码', oldPassword: '旧密码', enterCurrentPassword: '输入当前密码', newPassword: '新密码', enterNewPassword: '输入新密码', confirmNewPassword: '确认新密码', repeatNewPassword: '重复新密码', updatePassword: '更新密码',
    connLost: '连接已断开！', connLostDesc: '请立即检查您设备上的 WiFi 或移动数据连接。', connSlow: '连接缓慢 / 不稳定', connSlowDesc: '您的网络较慢，监控可能无法实时更新。',
    allNotifications: '所有通知', statusChangeEventsSession: '本次会话的状态变更事件', noNotifSession: '本次会话没有通知',
    notifTitle: '通知', markAllReadBtn: '全部标为已读', unreadLabel: '未读', allReadLabel: '全部已读', noNotifYet: '暂无通知', viewAllNotif: '查看所有通知', newBadge: '新',
    statusChange: '状态变更', rootCause: '根本原因', ipLabel: 'IP', responseLabel: '响应', urlLabel: '网址', timeLabel: '时间',
    liveNodesFeed: '实时节点动态', learnStatus: '了解状态含义', searchPlaceholder: '搜索...', allStatus: '全部状态', sortLabel: '排序', azLabel: 'A - Z', zaLabel: 'Z - A', newestLabel: '最新', oldestLabel: '最早',
    noMatchingNodes: '// 未找到匹配节点', resetFilters: '重置筛选', noServicesConfigured: '// 未配置服务', timeout: '超时',
    monitoringGuide: '监控指南', statusLegendConditions: '状态图例与条件', engineMonitoring: '监控引擎',
    engineDesc: '我们的系统以 3 种标准选项（30秒、60秒或120秒）定期执行健康检查。您在此仪表板看到的数据是实时（最新）的，通过 WebSocket 实时推送。',
    legendOnlineCond: 'HTTP 200-399 + RT ≤ 5,000ms', legendOnlineDesc: '网站健康、响应迅速，所有参数有效。',
    legendWarningCond: '缓慢 / WAF / 拦截', legendWarningDesc: '网站可访问但存在减速或轻微限制。',
    legendCriticalCond: '严重超时 / WAF 拦截', legendCriticalDesc: '极难访问，大部分请求失败或被拦截。',
    legendOfflineCond: '宕机 / 完全超时 / TCP 失败', legendOfflineDesc: '系统完全无法访问该网站。',
    monitoringStatus: '监控状态', loadingCaps: '加载中...', liveCaps: '实时', waitingData: '等待数据...', gTotal: '节点总数', gUptime: '正常运行率', gPeak: '离线峰值',
    statusDistribution: '状态分布', servicesLabel: '个服务', totalLabel: '总计', noServiceData: '暂无服务数据',
    monitoringTable: '监控表', noServicesMatch: '没有符合此筛选的服务', colWebsite: '网站', colUrl: '网址', colStatus: '状态', colHttp: 'HTTP', colResponse: '响应', colSsl: 'SSL', colLastCheck: '最后检查', validLabel: '有效', invalidLabel: '无效',
    mdOnline: '在线服务', mdCritical: '严重服务', mdOffline: '离线服务', mdAll: '所有服务', mdAlerts: '活动警报', mdRtRank: '响应时间排名', mdSla: 'SLA 概览',
    overallSla: '总体 SLA', serviceNameCol: '服务名称', slaValueCol: 'SLA 值', colService: '服务', colResponseTime: '响应时间', colIssue: '问题', noActiveAlerts: '✅ 无活动警报 — 所有系统运行正常', noServicesFound: '未找到服务',
    issueUnreachable: '服务无法访问', issueCriticalFail: '严重故障', issueStability: '稳定性警告',
    mdLegendTitle: '说明', legStatusTitle: '状态', legStatusDesc: 'OFFLINE：无法访问 · CRITICAL：部分失败 / 严重缓慢 · WARNING：性能下降 · ONLINE：正常', legHttpTitle: 'HTTP 代码', legHttpDesc: '2xx：成功 · 3xx：重定向 · 4xx：客户端错误 · 5xx：服务器错误 · “—” / 超时：无响应', legSslTitle: 'SSL', legSslDesc: '✓ 证书有效 · ✗ 无效 / 已过期 · — 未检查', legCheckTitle: '最后检查', legCheckDesc: '系统最近一次检测的时间',
    legSlaTitle: 'SLA', legSlaDesc: '服务等级协议（Service Level Agreement）— 服务可用且正常的时间占总监控时间的百分比。越高越可靠。', legSlaValueTitle: '各状态对应值', legSlaValueDesc: 'ONLINE 100% · WARNING 90% · CRITICAL 80% · OFFLINE 0%', legSlaOverallTitle: '总体 SLA', legSlaOverallDesc: '所有受监控服务的平均 SLA。',
    legAvgTitle: 'AVG RT（平均）', legAvgDesc: '平均响应时间（Average Response Time）— 所有服务响应时间的平均值；即 AVG RT 卡片上的数字。', legRtTitle: '响应时间', legRtDesc: '每个服务回复请求所需的时间 — 越小越快。', legRtColorTitle: '颜色代码', legRtColorDesc: '绿色 < 3000ms · 黄色 3000–10000ms · 红色 > 10000ms', legRtRankTitle: '排名', legRtRankDesc: '按响应最慢排序；前 3 名高亮显示。',
    tabOverview: '概览', tabPerformance: '性能', tabTimeline: '时间线', tabHistory: '历史',
    conditionWebsite: '网站状况', botChrome: 'CHROME 机器人', copyScreenshot: '复制截图', copied: '已复制！',
    cardServiceHealth: '服务健康', cardConnectivity: '连接性', cardSecurity: '安全', cardInfrastructure: '基础设施',
    rowStatus: '状态', rowHttpCode: 'HTTP 代码', rowResponseTime: '响应时间', rowTtfb: 'TTFB', rowLastCheck: '最后检查', rowIcmpPing: 'ICMP Ping', rowDnsStatus: 'DNS 状态', rowDnsLookup: 'DNS 查询时间', rowIpAddress: 'IP 地址', rowSslStatus: 'SSL 状态', rowExpiration: '到期日期', rowRemainingDays: '剩余天数', rowServer: '服务器', rowBotDetector: '机器人检测器',
    valFailed: '失败', valResolved: '已解析', valValid: '有效', valInvalid: '无效', valToday: '今天', valExpired: '已过期', valDays: '天', valUnknown: '未知',
    tlLoading: '加载时间线...', tlNoEvents: '尚无状态变更事件记录。', tlEventsNewest: '个状态变更事件 — 最新优先', tlDurationBar: '状态持续条', tlOldest: '最早', tlNewest: '最新', tlDuration: '持续', tlOngoing: '进行中',
    perfAvgResponse: '平均响应', perfSlowest: '最慢', perfFastest: '最快', perfResponseLast: '响应时间 — 最近', perfChecks: '次检查', perfTotalChecks: '总检查次数（样本）', perfSuccessfulChecks: '成功检查', perfSampleUptime: '样本正常运行率', visitWebsite: '访问网站', noHistory: '无历史记录', noAlertsService: '✅ 此服务没有警报', colHealth: '健康',
    websiteManagement: '网站管理', websitesConfigured: '个网站已配置', searchWebsiteUrl: '搜索网站或网址...', recommendations: '推荐',
    sortNameAz: '名称 (A - Z)', sortNameZa: '名称 (Z - A)', sortNewestCreated: '最新创建', sortOldestCreated: '最早创建',
    addWebsiteBtn: '+ 添加网站', limitReached: '已达上限', limitReachedTitle: '已达 100 个网站上限', addNewWebsiteTitle: '添加新网站',
    noWebsitesConfigured: '尚未配置网站。', clickAddWebsite: '点击"添加网站"开始。', noWebsitesMatch: '没有符合当前搜索或筛选的网站。',
    thWebsite: '网站', thUrlEndpoint: '网址 / 端点', thInterval: '间隔', thStatus: '状态', thHealth: '健康', thLatency: '延迟', thHttp: 'HTTP', thSsl: 'SSL', thNetLatencies: '网络延迟', thActions: '操作',
    editBtn: '编辑', deleteBtn: '删除', editWebsiteTitle: '编辑网站', addWebsiteModalTitle: '添加网站', confirmDeleteTitle: '确认删除',
    fieldName: '名称 *', fieldNamePh: '我的网站', fieldUrl: '网址 *', fieldDescription: '描述', fieldDescriptionPh: '可选描述', fieldInterval: '监控间隔',
    interval30: '30 秒（快速）', interval60: '60 秒（推荐）', interval120: '120 秒（正常）', secondsCurrent: '秒（当前）',
    takeScreenshot: '捕获页面截图（保存照片）', saveBtn: '保存', failedToSave: '保存失败',
    deleteConfirmPrefix: '删除', deleteConfirmSuffix: '？这也将永久删除数据库中的所有监控日志。',
    selectMode: '选择模式', selectAllTitle: '选择本页全部', selectedSuffix: '已选', clearSelectionBtn: '清除', deleteSelectedBtn: '删除所选', bulkDeleteTitle: '确认批量删除', bulkDeleteUnit: '个所选网站',
    deleteAllBtn: '删除全部', bulkDeleteFailed: '删除网站失败，请重试。', bulkDeleteAllWarning: '您即将永久删除所有网站及其全部监控日志与历史记录。此操作无法撤销。', bulkConfirmTypePrefix: '输入', bulkConfirmTypeSuffix: '以继续。', bulkDeleteAllKeyword: '删除全部',
    exp: '到期', ipLabelShort: 'IP',
    activityLogTitle: '活动日志', completeHistory: '完整历史', eventsLabel: '个事件', noEventsFound: '未找到事件。',
    colTransition: '转换', colNewStatus: '新状态', colTime: '时间',
    userManagement: '用户管理', usersLabel: '位用户', adminsUsed: '管理员已用', createUserBtn: '+ 创建用户', adminSlots: '管理员名额',
    thUsername: '用户名', thRole: '角色', thCreatedAt: '创建时间', noUsersFound: '未找到用户。', protectedLabel: '受保护', currentUserLabel: '当前用户', youLabel: '您',
    promoteBtn: '↑ 提升', demoteBtn: '↓ 降级', maxAdminsReached: '已达最多 3 名管理员', promoteToAdmin: '提升为管理员',
    deleteUserTitle: '删除用户', deleteUserConfirmPrefix: '删除', cannotBeUndone: '？此操作无法撤销。', createNewUser: '创建新用户',
    fieldPassword: '密码', passwordMinPh: '密码（至少 6 个字符）', roleViewer: '查看者', roleAdmin: '管理员', roleAdminPelindo: 'Admin Pelindo', fieldEmail: '邮箱 *', fieldTelegramOpt: 'TELEGRAM ID（可选）', createUserSubmit: '创建用户',
    refresh: '刷新', refreshing: '刷新中...', connecting: '连接中', allMonitoredNodes: '所有受监控节点', searchNodeUrl: '搜索节点名称或网址...',
    thEndpointName: '端点名称', thUrl: '网址', noWebsitesMonitored: '没有受监控的网站', addWebsitesToBegin: '添加网站以开始监控',
    cpuUsage: 'CPU 使用率', ramUsage: '内存使用率', networkConnection: '网络连接', netType: '类型', netName: '网络名称', endpointIpAddress: '端点与 IP 地址', httpCodeLabel: 'HTTP 代码', sslStatusLabel: 'SSL 状态', lastCheckLabel: '最后检查', failedRecheck: '触发重新检查失败',
    networkTopologyTitle: '网络拓扑', nodesLabel: '个节点', moreLabel: '更多', listLabel: '列表', mapLabel: '地图', showingAll: '显示全部', endpointsLabel: '个端点', noNodesMatch: '没有符合所选搜索或筛选的节点。', highLoadClick: '⚠️ 高负载 — 点击查看详情',
    srvResourceUsage: '资源使用', srvWorkerRuntime: 'WORKER 与运行时', srvNetworkInfo: '网络信息', srvAnalysis: '分析与建议', srvActiveWorkers: '活动 WORKER', srvQueueSize: '队列大小', srvGoroutines: 'GOROUTINE', srvWsConn: 'WS 连接', srvConnType: '连接类型', srvNetName: '网络名称', srvInterface: '接口', srvGateway: '网关', srvDnsResolver: 'DNS 解析器', srvLinkSpeed: '链路速度', srvDownload: '下载', srvUpload: '上传', srvLoading: '正在加载服务器数据…', srvAutoRefresh: '每 4 秒自动刷新 · 按 Esc 关闭', srvLocalSystem: '本地系统', srvUpdated: '已更新', srvNormal: '正常', srvExceeds: '超过阈值',
    createAccount: '创建账户', welcome: '欢迎', signUpMonitor: '注册以监控服务', signInAccess: '登录以访问监控仪表板',
    usernamePh: '用户名', emailReqPh: '邮箱 *', telegramOptPh: 'Telegram ID（可选）', passwordPh: '密码', register: '注册', signIn: '登录',
    alreadyHaveAccount: '已有账户？ ', needAccount: '需要账户？ ', signInLink: '登录', registerHere: '在此注册', completeCaptcha: '请完成人机验证', regSuccess: '注册成功！您的账户在登录前需要管理员批准。', rememberMe: '记住我', telegramPhonePh: 'Telegram 电话号码（如 0812xxxxxxx）', regFailed: '注册失败。', loginFailed: '登录失败。请检查凭据。', loginSuccess: '登录成功',
  },
  ja: {
    dashboard: 'ダッシュボード', websites: 'ウェブサイト', activity: 'アクティビティ', users: 'ユーザー', notifications: '通知', incidents: 'インシデントセンター',
    online: 'オンライン', offline: 'オフライン', critical: 'クリティカル', warning: '警告', unknown: '不明', pending: '保留中', total: '合計', alerts: 'アラート',
    avgRt: '平均RT',
    profile: 'プロファイル', settings: '設定', about: '詳細', logout: 'ログアウト', save: '保存', cancel: 'キャンセル', delete: '削除', edit: '編集', back: '戻る', show: '表示', hide: '非表示',
    createUser: 'ユーザー作成', addWebsite: 'サイト追加', clearAll: 'すべて消去', markAllRead: 'すべて既読',
    close: '閉じる', reset: 'リセット', search: '検索', confirm: '確認', apply: '適用', processing: '処理中...', saving: '保存中...', creating: '作成中...', loading: '読み込み中...', sending: '送信中...', remove: '削除',
    enterFullScreen: 'フルスクリーン', exitFullScreen: 'フルスクリーン解除', chooseTheme: 'テーマを選択', lightMode: 'ライトモード', darkMode: 'ダークモード',
    detail: '詳細',
    systemSettings: 'システム設定', themeSelection: 'SF テーマ選択', languageLabel: '言語', monitoringPreferences: 'モニタリング設定',
    notifSound: '通知音', notifSoundDesc: '新しいアラート時に SF アラームを鳴らす',
    desktopNotif: 'デスクトップ通知', desktopNotifDesc: 'サイトがオフライン/クリティカル時に OS 通知をポップアップ（タブが背景でも）',
    autoAck: '復旧の自動確認', autoAckDesc: 'サイトが復旧（オンライン）したら通知を自動的に既読にする',
    saveApply: '保存して適用', noDesktopSupport: 'このブラウザはデスクトップ通知に対応していません。', notifDenied: '通知の許可が拒否されました。ブラウザのサイト設定で有効にしてください。',
    aboutTitle: 'SPMT モニタリングについて', systemNameSub: 'NOC コントロールパネル · Pelindo Multi Terminal',
    aboutPurpose: '目的', aboutPurposeDesc: 'Pelindo Multi Terminal の全ウェブサイトとデジタルサービスの可用性とパフォーマンスを 24時間365日リアルタイムで監視します。',
    aboutHow: '仕組み', aboutHowDesc: 'Go バックエンドが 30〜120 秒ごと（設定可能）に HTTP/DNS/ICMP/TCP チェックを実行します。結果は WebSocket で送信され、更新なしで即座に表示されます。',
    aboutSecurity: 'セキュリティ', aboutSecurityDesc: 'JWT トークン + ロールベースアクセス：スーパー管理者（フルアクセス）、管理者（サイト管理）、閲覧者（読み取り専用）。',
    aboutFeatures: '機能', aboutFeaturesDesc: 'ネットワークトポロジ（最大50サイト）· モニタリンググラフ（100点）· アクティビティログ · 自動通知。',
    sinergiCoreValues: 'シナジーとコアバリュー',
    brandPelindoDesc: '国家港湾サービスの統合。', brandDananDesc: '統合デジタル技術のイノベーション。', brandBumnDesc: '国家経済のデジタル変革。', brandAkhlakDesc: '高潔な労働文化のコアバリュー。',
    logoutQ: 'ログアウト？', logoutConfirm: 'ログアウトしてもよろしいですか？',
    customizationProfile: 'カスタマイズとプロファイル', uploadPhoto: '写真をアップロード', roleLabel: 'ロール', generalSettings: '一般設定', securityTab: 'セキュリティ',
    personalNotifSettings: '個人通知設定', currentEmailAddress: '現在のメールアドレス', required: '必須', noEmailYet: 'メール未登録',
    changeBtn: '変更', setEmailBtn: 'メール設定', closeBtn: '閉じる', updateEmailIdentity: 'メール ID を更新',
    confirmCurrentEmail: '現在のメールを確認', typeExistingEmail: '既存のメールを入力...', newEmailAddress: '新しいメールアドレス', enterNewEmail: '新しいメールを入力...', retypeNewEmail: '新しいメールを再入力', confirmNewEmail: '新しいメールを確認...',
    confirmIdentityChange: 'ID 変更を確認',
    telegramIntegration: 'TELEGRAM 連携', optional: '任意', telegramPlaceholder: '@ユーザー名 または Chat ID...', telegramHelp: 'メインメールに届かない場合のバックアップアラートに使用。', updateBtn: '更新', linkBtn: '連携',
    testSystemNotif: 'システム通知テスト', testSmtpDesc: 'SMTP とメール設定を即座に検証', sendTestEmail: 'テストメール送信',
    changeAccountPassword: 'アカウントパスワード変更', oldPassword: '旧パスワード', enterCurrentPassword: '現在のパスワードを入力', newPassword: '新しいパスワード', enterNewPassword: '新しいパスワードを入力', confirmNewPassword: '新しいパスワードを確認', repeatNewPassword: '新しいパスワードを再入力', updatePassword: 'パスワード更新',
    connLost: '接続が切断されました！', connLostDesc: 'デバイスの WiFi またはモバイルデータ接続をすぐに確認してください。', connSlow: '接続が遅い / 不安定', connSlowDesc: 'ネットワークが遅くなっています。モニタリングがリアルタイムで更新されない場合があります。',
    allNotifications: 'すべての通知', statusChangeEventsSession: 'このセッションのステータス変更イベント', noNotifSession: 'このセッションに通知はありません',
    notifTitle: '通知', markAllReadBtn: 'すべて既読', unreadLabel: '未読', allReadLabel: 'すべて既読', noNotifYet: '通知はまだありません', viewAllNotif: 'すべての通知を表示', newBadge: '新着',
    statusChange: 'ステータス変更', rootCause: '根本原因', ipLabel: 'IP', responseLabel: '応答', urlLabel: 'URL', timeLabel: '時刻',
    liveNodesFeed: 'ライブノードフィード', learnStatus: 'ステータスの意味を学ぶ', searchPlaceholder: '検索...', allStatus: 'すべてのステータス', sortLabel: '並べ替え', azLabel: 'A - Z', zaLabel: 'Z - A', newestLabel: '新しい順', oldestLabel: '古い順',
    noMatchingNodes: '// 一致するノードがありません', resetFilters: 'フィルターをリセット', noServicesConfigured: '// サービス未設定', timeout: 'タイムアウト',
    monitoringGuide: 'モニタリングガイド', statusLegendConditions: 'ステータス凡例と条件', engineMonitoring: 'モニタリングエンジン',
    engineDesc: '当システムは 3 つの標準オプション（30秒、60秒、120秒）で定期的にヘルスチェックを実行します。このダッシュボードのデータはリアルタイム（最新）で、WebSocket 経由でライブ配信されます。',
    legendOnlineCond: 'HTTP 200-399 + RT ≤ 5,000ms', legendOnlineDesc: 'サイトは健全で応答が速く、すべてのパラメータが有効です。',
    legendWarningCond: '低速 / WAF / インターセプト', legendWarningDesc: 'サイトにはアクセスできますが、遅延や軽微な制限があります。',
    legendCriticalCond: '深刻なタイムアウト / WAF ブロック', legendCriticalDesc: 'アクセスが非常に困難で、ほとんどのリクエストが失敗またはブロックされます。',
    legendOfflineCond: 'ダウン / 完全タイムアウト / TCP 失敗', legendOfflineDesc: 'システムからサイトに全く到達できません。',
    monitoringStatus: 'モニタリングステータス', loadingCaps: '読み込み中...', liveCaps: 'ライブ', waitingData: 'データ待機中...', gTotal: '総ノード数', gUptime: '稼働率', gPeak: 'オフラインピーク',
    statusDistribution: 'ステータス分布', servicesLabel: 'サービス', totalLabel: '合計', noServiceData: 'サービスデータがありません',
    monitoringTable: 'モニタリングテーブル', noServicesMatch: 'このフィルターに一致するサービスはありません', colWebsite: 'ウェブサイト', colUrl: 'URL', colStatus: 'ステータス', colHttp: 'HTTP', colResponse: '応答', colSsl: 'SSL', colLastCheck: '最終チェック', validLabel: '有効', invalidLabel: '無効',
    mdOnline: 'オンラインサービス', mdCritical: 'クリティカルサービス', mdOffline: 'オフラインサービス', mdAll: 'すべてのサービス', mdAlerts: 'アクティブなアラート', mdRtRank: '応答時間ランキング', mdSla: 'SLA 概要',
    overallSla: '全体 SLA', serviceNameCol: 'サービス名', slaValueCol: 'SLA 値', colService: 'サービス', colResponseTime: '応答時間', colIssue: '問題', noActiveAlerts: '✅ アクティブなアラートなし — すべてのシステムが正常です', noServicesFound: 'サービスが見つかりません',
    issueUnreachable: 'サービスに到達不可', issueCriticalFail: '重大な障害', issueStability: '安定性の警告',
    mdLegendTitle: '凡例', legStatusTitle: 'ステータス', legStatusDesc: 'OFFLINE：到達不可 · CRITICAL：部分的な障害 / 非常に遅い · WARNING：性能低下 · ONLINE：正常', legHttpTitle: 'HTTP コード', legHttpDesc: '2xx：成功 · 3xx：リダイレクト · 4xx：クライアントエラー · 5xx：サーバーエラー · 「—」/ タイムアウト：応答なし', legSslTitle: 'SSL', legSslDesc: '✓ 有効な証明書 · ✗ 無効 / 期限切れ · — 未チェック', legCheckTitle: '最終チェック', legCheckDesc: 'システムによる最新の確認時刻',
    legSlaTitle: 'SLA', legSlaDesc: 'Service Level Agreement — 総監視時間に対してサービスが利用可能かつ正常だった時間の割合。高いほど信頼性が高い。', legSlaValueTitle: 'ステータス別の値', legSlaValueDesc: 'ONLINE 100% · WARNING 90% · CRITICAL 80% · OFFLINE 0%', legSlaOverallTitle: '全体 SLA', legSlaOverallDesc: '監視中の全サービスの平均 SLA。',
    legAvgTitle: 'AVG RT（平均）', legAvgDesc: 'Average Response Time — 全サービスの応答時間の平均値。AVG RT カードに表示される数値です。', legRtTitle: '応答時間', legRtDesc: '各サービスが応答するまでの時間 — 小さいほど速い。', legRtColorTitle: 'カラーコード', legRtColorDesc: '緑 < 3000ms · 黄 3000–10000ms · 赤 > 10000ms', legRtRankTitle: 'ランキング', legRtRankDesc: '応答が遅い順に並び替え。上位3件を強調表示。',
    tabOverview: '概要', tabPerformance: 'パフォーマンス', tabTimeline: 'タイムライン', tabHistory: '履歴',
    conditionWebsite: 'ウェブサイトの状態', botChrome: 'CHROME ボット', copyScreenshot: 'スクショをコピー', copied: 'コピーしました！',
    cardServiceHealth: 'サービス健全性', cardConnectivity: '接続性', cardSecurity: 'セキュリティ', cardInfrastructure: 'インフラ',
    rowStatus: 'ステータス', rowHttpCode: 'HTTP コード', rowResponseTime: '応答時間', rowTtfb: 'TTFB', rowLastCheck: '最終チェック', rowIcmpPing: 'ICMP Ping', rowDnsStatus: 'DNS ステータス', rowDnsLookup: 'DNS ルックアップ時間', rowIpAddress: 'IP アドレス', rowSslStatus: 'SSL ステータス', rowExpiration: '有効期限', rowRemainingDays: '残り日数', rowServer: 'サーバー', rowBotDetector: 'ボット検出器',
    valFailed: '失敗', valResolved: '解決済み', valValid: '有効', valInvalid: '無効', valToday: '今日', valExpired: '期限切れ', valDays: '日', valUnknown: '不明',
    tlLoading: 'タイムライン読み込み中...', tlNoEvents: 'ステータス変更イベントはまだ記録されていません。', tlEventsNewest: '件のステータス変更イベント — 新しい順', tlDurationBar: 'ステータス継続バー', tlOldest: '最古', tlNewest: '最新', tlDuration: '継続', tlOngoing: '継続中',
    perfAvgResponse: '平均応答', perfSlowest: '最も遅い', perfFastest: '最も速い', perfResponseLast: '応答時間 — 直近', perfChecks: '回のチェック', perfTotalChecks: '総チェック数（サンプル）', perfSuccessfulChecks: '成功したチェック', perfSampleUptime: 'サンプル稼働率', visitWebsite: 'サイトを開く', noHistory: '履歴なし', noAlertsService: '✅ このサービスにアラートはありません', colHealth: '健全性',
    websiteManagement: 'ウェブサイト管理', websitesConfigured: 'サイト設定済み', searchWebsiteUrl: 'サイトまたは URL を検索...', recommendations: 'おすすめ',
    sortNameAz: '名前 (A - Z)', sortNameZa: '名前 (Z - A)', sortNewestCreated: '作成が新しい順', sortOldestCreated: '作成が古い順',
    addWebsiteBtn: '+ サイト追加', limitReached: '上限に達しました', limitReachedTitle: '100 サイトの上限に達しました', addNewWebsiteTitle: '新しいサイトを追加',
    noWebsitesConfigured: 'サイトが設定されていません。', clickAddWebsite: '「サイト追加」をクリックして開始。', noWebsitesMatch: '現在の検索またはフィルターに一致するサイトはありません。',
    thWebsite: 'ウェブサイト', thUrlEndpoint: 'URL / エンドポイント', thInterval: '間隔', thStatus: 'ステータス', thHealth: '健全性', thLatency: 'レイテンシ', thHttp: 'HTTP', thSsl: 'SSL', thNetLatencies: 'ネットワーク遅延', thActions: 'アクション',
    editBtn: '編集', deleteBtn: '削除', editWebsiteTitle: 'サイトを編集', addWebsiteModalTitle: 'サイトを追加', confirmDeleteTitle: '削除の確認',
    fieldName: '名前 *', fieldNamePh: 'マイサイト', fieldUrl: 'URL *', fieldDescription: '説明', fieldDescriptionPh: '任意の説明', fieldInterval: 'モニタリング間隔',
    interval30: '30 秒（高速）', interval60: '60 秒（推奨）', interval120: '120 秒（通常）', secondsCurrent: '秒（現在）',
    takeScreenshot: 'ページのスクショを取得（写真を保存）', saveBtn: '保存', failedToSave: '保存に失敗しました',
    deleteConfirmPrefix: '削除', deleteConfirmSuffix: '？データベースからすべてのモニタリングログも完全に削除されます。',
    selectMode: '選択モード', selectAllTitle: 'このページをすべて選択', selectedSuffix: '件選択', clearSelectionBtn: 'クリア', deleteSelectedBtn: '選択を削除', bulkDeleteTitle: '一括削除の確認', bulkDeleteUnit: '件の選択したサイト',
    deleteAllBtn: 'すべて削除', bulkDeleteFailed: 'サイトの削除に失敗しました。もう一度お試しください。', bulkDeleteAllWarning: 'すべてのウェブサイトと、そのすべてのモニタリングログ・履歴を完全に削除しようとしています。この操作は取り消せません。', bulkConfirmTypePrefix: '続行するには', bulkConfirmTypeSuffix: 'と入力してください。', bulkDeleteAllKeyword: 'すべて削除',
    exp: '期限', ipLabelShort: 'IP',
    activityLogTitle: 'アクティビティログ', completeHistory: '完全な履歴', eventsLabel: '件のイベント', noEventsFound: 'イベントが見つかりません。',
    colTransition: '遷移', colNewStatus: '新ステータス', colTime: '時刻',
    userManagement: 'ユーザー管理', usersLabel: '人のユーザー', adminsUsed: '管理者使用中', createUserBtn: '+ ユーザー作成', adminSlots: '管理者スロット',
    thUsername: 'ユーザー名', thRole: 'ロール', thCreatedAt: '作成日', noUsersFound: 'ユーザーが見つかりません。', protectedLabel: '保護済み', currentUserLabel: '現在のユーザー', youLabel: 'あなた',
    promoteBtn: '↑ 昇格', demoteBtn: '↓ 降格', maxAdminsReached: '管理者は最大 3 名です', promoteToAdmin: '管理者に昇格',
    deleteUserTitle: 'ユーザー削除', deleteUserConfirmPrefix: '削除', cannotBeUndone: '？この操作は元に戻せません。', createNewUser: '新規ユーザー作成',
    fieldPassword: 'パスワード', passwordMinPh: 'パスワード（6文字以上）', roleViewer: '閲覧者', roleAdmin: '管理者', roleAdminPelindo: 'Admin Pelindo', fieldEmail: 'メール *', fieldTelegramOpt: 'TELEGRAM ID（任意）', createUserSubmit: 'ユーザー作成',
    refresh: '更新', refreshing: '更新中...', connecting: '接続中', allMonitoredNodes: '監視中の全ノード', searchNodeUrl: 'ノード名または URL を検索...',
    thEndpointName: 'エンドポイント名', thUrl: 'URL', noWebsitesMonitored: '監視中のサイトはありません', addWebsitesToBegin: 'サイトを追加してモニタリングを開始',
    cpuUsage: 'CPU 使用率', ramUsage: 'RAM 使用率', networkConnection: 'ネットワーク接続', netType: 'タイプ', netName: 'ネットワーク名', endpointIpAddress: 'エンドポイントと IP アドレス', httpCodeLabel: 'HTTP コード', sslStatusLabel: 'SSL ステータス', lastCheckLabel: '最終チェック', failedRecheck: '再チェックの起動に失敗しました',
    networkTopologyTitle: 'ネットワークトポロジ', nodesLabel: 'ノード', moreLabel: 'もっと見る', listLabel: 'リスト', mapLabel: 'マップ', showingAll: 'すべて表示', endpointsLabel: 'エンドポイント', noNodesMatch: '選択した検索またはフィルターに一致するノードはありません。', highLoadClick: '⚠️ 高負荷 — クリックで詳細',
    srvResourceUsage: 'リソース使用状況', srvWorkerRuntime: 'ワーカーとランタイム', srvNetworkInfo: 'ネットワーク情報', srvAnalysis: '分析と推奨', srvActiveWorkers: 'アクティブワーカー', srvQueueSize: 'キューサイズ', srvGoroutines: 'ゴルーチン', srvWsConn: 'WS 接続', srvConnType: '接続タイプ', srvNetName: 'ネットワーク名', srvInterface: 'インターフェース', srvGateway: 'ゲートウェイ', srvDnsResolver: 'DNS リゾルバー', srvLinkSpeed: 'リンク速度', srvDownload: 'ダウンロード', srvUpload: 'アップロード', srvLoading: 'サーバーデータを読み込み中…', srvAutoRefresh: '4秒ごとに自動更新 · Esc で閉じる', srvLocalSystem: 'ローカルシステム', srvUpdated: '更新', srvNormal: '正常', srvExceeds: 'しきい値超過',
    createAccount: 'アカウント作成', welcome: 'ようこそ', signUpMonitor: 'サービスを監視するために登録', signInAccess: 'モニタリングダッシュボードにアクセスするためにサインイン',
    usernamePh: 'ユーザー名', emailReqPh: 'メール *', telegramOptPh: 'Telegram ID（任意）', passwordPh: 'パスワード', register: '登録', signIn: 'サインイン',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？ ', needAccount: 'アカウントが必要ですか？ ', signInLink: 'サインイン', registerHere: 'こちらで登録', completeCaptcha: 'CAPTCHA を完了してください', regSuccess: '登録に成功しました！ログインする前に管理者の承認が必要です。', rememberMe: 'ログイン情報を保存', telegramPhonePh: 'Telegram 電話番号（例: 0812xxxxxxx）', regFailed: '登録に失敗しました。', loginFailed: 'ログインに失敗しました。資格情報を確認してください。', loginSuccess: 'ログインしました',
  },
  ru: {
    dashboard: 'Панель', websites: 'Сайты', activity: 'Активность', users: 'Пользователи', notifications: 'Уведомления', incidents: 'Центр инцидентов',
    online: 'ОНЛАЙН', offline: 'ОФФЛАЙН', critical: 'КРИТИЧЕСКИЙ', warning: 'ПРЕДУПРЕЖД.', unknown: 'НЕИЗВЕСТНО', pending: 'ОЖИДАНИЕ', total: 'ВСЕГО', alerts: 'ТРЕВОГИ',
    avgRt: 'СРЕД. RT',
    profile: 'Профиль', settings: 'Настройки', about: 'О программе', logout: 'Выйти', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Правка', back: 'Назад', show: 'Показать', hide: 'Скрыть',
    createUser: 'СОЗДАТЬ ЮЗЕРА', addWebsite: 'ДОБАВИТЬ САЙТ', clearAll: 'Очистить все', markAllRead: 'Прочитать все',
    close: 'Закрыть', reset: 'Сброс', search: 'Поиск', confirm: 'Подтвердить', apply: 'Применить', processing: 'Обработка...', saving: 'Сохранение...', creating: 'Создание...', loading: 'Загрузка...', sending: 'Отправка...', remove: 'Удалить',
    enterFullScreen: 'Полный экран', exitFullScreen: 'Выйти из полного экрана', chooseTheme: 'ВЫБЕРИТЕ ТЕМУ', lightMode: 'Светлая тема', darkMode: 'Тёмная тема',
    detail: 'Детали',
    systemSettings: 'Настройки системы', themeSelection: 'ВЫБОР SCI-FI ТЕМЫ', languageLabel: 'ЯЗЫК', monitoringPreferences: 'НАСТРОЙКИ МОНИТОРИНГА',
    notifSound: 'Звук уведомлений', notifSoundDesc: 'Проигрывать sci-fi сигнал при новой тревоге',
    desktopNotif: 'Уведомления рабочего стола', desktopNotifDesc: 'Всплывающее уведомление ОС, когда сайт ОФФЛАЙН/КРИТИЧЕСКИЙ (даже если вкладка в фоне)',
    autoAck: 'Авто-подтверждение восстановления', autoAckDesc: 'Автоматически отмечать уведомления прочитанными при восстановлении сайта (ОНЛАЙН)',
    saveApply: 'Сохранить и применить', noDesktopSupport: 'Этот браузер не поддерживает уведомления рабочего стола.', notifDenied: 'Разрешение на уведомления отклонено. Включите его в настройках сайта в браузере.',
    aboutTitle: 'О SPMT Monitoring', systemNameSub: 'Панель управления NOC · Pelindo Multi Terminal',
    aboutPurpose: 'Цель', aboutPurposeDesc: 'Мониторинг доступности и производительности всех сайтов и цифровых сервисов Pelindo Multi Terminal в реальном времени 24/7.',
    aboutHow: 'Как это работает', aboutHowDesc: 'Go-бэкенд выполняет проверки HTTP/DNS/ICMP/TCP каждые 30–120 секунд (настраивается). Результаты отправляются через WebSocket и отображаются мгновенно без обновления.',
    aboutSecurity: 'Безопасность', aboutSecurityDesc: 'JWT-токен + ролевой доступ: SuperAdmin (полный доступ), Admin (управление сайтами), Viewer (только чтение).',
    aboutFeatures: 'Возможности', aboutFeaturesDesc: 'Сетевая топология (макс. 50 сайтов) · График мониторинга (100 точек) · Журнал активности · Автоуведомления.',
    sinergiCoreValues: 'Синергия и ценности',
    brandPelindoDesc: 'Интеграция национальных портовых услуг.', brandDananDesc: 'Интегрированные цифровые технологические инновации.', brandBumnDesc: 'Цифровая трансформация национальной экономики.', brandAkhlakDesc: 'Основные ценности благородной рабочей культуры.',
    logoutQ: 'Выйти?', logoutConfirm: 'Вы уверены, что хотите выйти?',
    customizationProfile: 'Настройка и профиль', uploadPhoto: 'Загрузить фото', roleLabel: 'Роль', generalSettings: 'Общие настройки', securityTab: 'Безопасность',
    personalNotifSettings: 'ЛИЧНЫЕ НАСТРОЙКИ УВЕДОМЛЕНИЙ', currentEmailAddress: 'ТЕКУЩИЙ EMAIL', required: 'ОБЯЗАТЕЛЬНО', noEmailYet: 'Email ещё не зарегистрирован',
    changeBtn: 'ИЗМЕНИТЬ', setEmailBtn: 'ЗАДАТЬ EMAIL', closeBtn: 'ЗАКРЫТЬ', updateEmailIdentity: 'ОБНОВИТЬ EMAIL',
    confirmCurrentEmail: 'ПОДТВЕРДИТЕ ТЕКУЩИЙ EMAIL', typeExistingEmail: 'Введите ваш текущий email...', newEmailAddress: 'НОВЫЙ EMAIL', enterNewEmail: 'Введите новый email...', retypeNewEmail: 'ПОВТОРИТЕ НОВЫЙ EMAIL', confirmNewEmail: 'Подтвердите новый email...',
    confirmIdentityChange: 'ПОДТВЕРДИТЬ СМЕНУ',
    telegramIntegration: 'ИНТЕГРАЦИЯ TELEGRAM', optional: 'НЕОБЯЗАТЕЛЬНО', telegramPlaceholder: '@username или Chat ID...', telegramHelp: 'Используется для резервных тревог, если основной email недоступен.', updateBtn: 'ОБНОВИТЬ', linkBtn: 'ПРИВЯЗАТЬ',
    testSystemNotif: 'ТЕСТ УВЕДОМЛЕНИЙ', testSmtpDesc: 'Мгновенно проверьте настройки SMTP и Email', sendTestEmail: 'ОТПРАВИТЬ ТЕСТ',
    changeAccountPassword: 'СМЕНА ПАРОЛЯ АККАУНТА', oldPassword: 'СТАРЫЙ ПАРОЛЬ', enterCurrentPassword: 'Введите текущий пароль', newPassword: 'НОВЫЙ ПАРОЛЬ', enterNewPassword: 'Введите новый пароль', confirmNewPassword: 'ПОДТВЕРДИТЕ НОВЫЙ ПАРОЛЬ', repeatNewPassword: 'Повторите новый пароль', updatePassword: 'Обновить пароль',
    connLost: 'СОЕДИНЕНИЕ ПОТЕРЯНО!', connLostDesc: 'Пожалуйста, немедленно проверьте подключение WiFi или мобильных данных на вашем устройстве.', connSlow: 'МЕДЛЕННОЕ / НЕСТАБИЛЬНОЕ СОЕДИНЕНИЕ', connSlowDesc: 'Ваша сеть работает медленно. Мониторинг может не обновляться в реальном времени.',
    allNotifications: 'Все уведомления', statusChangeEventsSession: 'События изменения статуса в этой сессии', noNotifSession: 'Нет уведомлений в этой сессии',
    notifTitle: 'Уведомления', markAllReadBtn: 'Прочитать все', unreadLabel: 'непрочитано', allReadLabel: 'Все прочитаны', noNotifYet: 'Пока нет уведомлений', viewAllNotif: 'Показать все уведомления', newBadge: 'НОВОЕ',
    statusChange: 'Изменение статуса', rootCause: 'Первопричина', ipLabel: 'IP', responseLabel: 'Ответ', urlLabel: 'URL', timeLabel: 'Время',
    liveNodesFeed: 'ЖИВАЯ ЛЕНТА УЗЛОВ', learnStatus: 'Узнать значения статусов', searchPlaceholder: 'Поиск...', allStatus: 'Все статусы', sortLabel: 'Сортировка', azLabel: 'А - Я', zaLabel: 'Я - А', newestLabel: 'Новые', oldestLabel: 'Старые',
    noMatchingNodes: '// СОВПАДАЮЩИХ УЗЛОВ НЕ НАЙДЕНО', resetFilters: 'Сбросить фильтры', noServicesConfigured: '// СЕРВИСЫ НЕ НАСТРОЕНЫ', timeout: 'ТАЙМАУТ',
    monitoringGuide: 'РУКОВОДСТВО ПО МОНИТОРИНГУ', statusLegendConditions: 'Легенда статусов и условия', engineMonitoring: 'ДВИЖОК МОНИТОРИНГА',
    engineDesc: 'Наша система выполняет периодические проверки работоспособности с 3 стандартными вариантами (30с, 60с или 120с). Данные на этой панели — в реальном времени, передаются по WebSocket.',
    legendOnlineCond: 'HTTP 200-399 + RT ≤ 5 000мс', legendOnlineDesc: 'Сайт работает, отзывчив, все параметры в норме.',
    legendWarningCond: 'Медленно / WAF / Перехват', legendWarningDesc: 'Сайт доступен, но есть замедления или незначительные ограничения.',
    legendCriticalCond: 'Сильный таймаут / Блокировка WAF', legendCriticalDesc: 'Доступ крайне затруднён, большинство запросов не выполняются или блокируются.',
    legendOfflineCond: 'Недоступен / Полный таймаут / Сбой TCP', legendOfflineDesc: 'Сайт полностью недоступен для системы.',
    monitoringStatus: 'СТАТУС МОНИТОРИНГА', loadingCaps: 'ЗАГРУЗКА...', liveCaps: 'ЖИВОЙ', waitingData: 'Ожидание данных...', gTotal: 'ВСЕГО УЗЛОВ', gUptime: 'АПТАЙМ', gPeak: 'ПИК ОФФЛАЙН',
    statusDistribution: 'РАСПРЕДЕЛЕНИЕ СТАТУСОВ', servicesLabel: 'сервисов', totalLabel: 'Всего', noServiceData: 'Пока нет данных о сервисах',
    monitoringTable: 'ТАБЛИЦА МОНИТОРИНГА', noServicesMatch: 'Нет сервисов, соответствующих этому фильтру', colWebsite: 'Сайт', colUrl: 'URL', colStatus: 'Статус', colHttp: 'HTTP', colResponse: 'Ответ', colSsl: 'SSL', colLastCheck: 'Послед. проверка', validLabel: 'Действителен', invalidLabel: 'Недействителен',
    mdOnline: 'Онлайн-сервисы', mdCritical: 'Критические сервисы', mdOffline: 'Оффлайн-сервисы', mdAll: 'Все сервисы', mdAlerts: 'Активные тревоги', mdRtRank: 'Рейтинг времени ответа', mdSla: 'Обзор SLA',
    overallSla: 'Общий SLA', serviceNameCol: 'НАЗВАНИЕ СЕРВИСА', slaValueCol: 'ЗНАЧЕНИЕ SLA', colService: 'Сервис', colResponseTime: 'Время ответа', colIssue: 'Проблема', noActiveAlerts: '✅ Нет активных тревог — все системы работают', noServicesFound: 'Сервисы не найдены',
    issueUnreachable: 'Сервис недоступен', issueCriticalFail: 'Критический сбой', issueStability: 'Предупреждение о стабильности',
    mdLegendTitle: 'Пояснение', legStatusTitle: 'Статус', legStatusDesc: 'OFFLINE: недоступен · CRITICAL: частичный сбой / очень медленно · WARNING: снижение производительности · ONLINE: норма', legHttpTitle: 'Код HTTP', legHttpDesc: '2xx: успех · 3xx: перенаправление · 4xx: ошибка клиента · 5xx: ошибка сервера · «—» / Таймаут: нет ответа', legSslTitle: 'SSL', legSslDesc: '✓ действительный сертификат · ✗ недействительный / истёк · — не проверено', legCheckTitle: 'Послед. проверка', legCheckDesc: 'Время последней проверки системой',
    legSlaTitle: 'SLA', legSlaDesc: 'Service Level Agreement — процент времени, когда сервис был доступен и исправен, от всего времени мониторинга. Чем выше, тем надёжнее.', legSlaValueTitle: 'Значение по статусу', legSlaValueDesc: 'ONLINE 100% · WARNING 90% · CRITICAL 80% · OFFLINE 0%', legSlaOverallTitle: 'Общий SLA', legSlaOverallDesc: 'Средний SLA по всем отслеживаемым сервисам.',
    legAvgTitle: 'AVG RT (Среднее)', legAvgDesc: 'Average Response Time — среднее время ответа по всем сервисам; это число на карточке AVG RT.', legRtTitle: 'Время ответа', legRtDesc: 'Сколько каждый сервис отвечает на запрос — меньше значит быстрее.', legRtColorTitle: 'Цветовой код', legRtColorDesc: 'Зелёный < 3000ms · Жёлтый 3000–10000ms · Красный > 10000ms', legRtRankTitle: 'Рейтинг', legRtRankDesc: 'Сортировка по самому медленному ответу; топ-3 выделены.',
    tabOverview: 'ОБЗОР', tabPerformance: 'ПРОИЗВОДИТЕЛЬНОСТЬ', tabTimeline: 'ХРОНОЛОГИЯ', tabHistory: 'ИСТОРИЯ',
    conditionWebsite: 'СОСТОЯНИЕ САЙТА', botChrome: 'CHROME-БОТ', copyScreenshot: 'Копировать скриншот', copied: 'Скопировано!',
    cardServiceHealth: 'ЗДОРОВЬЕ СЕРВИСА', cardConnectivity: 'ПОДКЛЮЧЕНИЕ', cardSecurity: 'БЕЗОПАСНОСТЬ', cardInfrastructure: 'ИНФРАСТРУКТУРА',
    rowStatus: 'Статус', rowHttpCode: 'Код HTTP', rowResponseTime: 'Время ответа', rowTtfb: 'TTFB', rowLastCheck: 'Послед. проверка', rowIcmpPing: 'ICMP Ping', rowDnsStatus: 'Статус DNS', rowDnsLookup: 'Время DNS-запроса', rowIpAddress: 'IP-адрес', rowSslStatus: 'Статус SSL', rowExpiration: 'Дата истечения', rowRemainingDays: 'Осталось дней', rowServer: 'Сервер', rowBotDetector: 'Детектор ботов',
    valFailed: 'Сбой', valResolved: 'Разрешён', valValid: 'Действителен', valInvalid: 'Недействителен', valToday: 'Сегодня', valExpired: 'Истёк', valDays: 'дн.', valUnknown: 'Неизвестно',
    tlLoading: 'Загрузка хронологии...', tlNoEvents: 'События изменения статуса ещё не записаны.', tlEventsNewest: 'событий изменения статуса — новые первыми', tlDurationBar: 'ПОЛОСА ДЛИТЕЛЬНОСТИ СТАТУСА', tlOldest: 'Старейшее', tlNewest: 'Новейшее', tlDuration: 'Длительность', tlOngoing: 'продолжается',
    perfAvgResponse: 'Сред. ответ', perfSlowest: 'Самый медленный', perfFastest: 'Самый быстрый', perfResponseLast: 'ВРЕМЯ ОТВЕТА — ПОСЛЕДНИЕ', perfChecks: 'ПРОВЕРОК', perfTotalChecks: 'Всего проверок (выборка)', perfSuccessfulChecks: 'Успешные проверки', perfSampleUptime: 'Аптайм выборки', visitWebsite: 'ПЕРЕЙТИ НА САЙТ', noHistory: 'Нет истории', noAlertsService: '✅ Нет тревог для этого сервиса', colHealth: 'Здоровье',
    websiteManagement: 'Управление сайтами', websitesConfigured: 'сайтов настроено', searchWebsiteUrl: 'Поиск сайта или URL...', recommendations: 'РЕКОМЕНДАЦИИ',
    sortNameAz: 'Имя (А - Я)', sortNameZa: 'Имя (Я - А)', sortNewestCreated: 'Новые по дате', sortOldestCreated: 'Старые по дате',
    addWebsiteBtn: '+ Добавить сайт', limitReached: 'Лимит достигнут', limitReachedTitle: 'Достигнут лимит 100 сайтов', addNewWebsiteTitle: 'Добавить новый сайт',
    noWebsitesConfigured: 'Сайты не настроены.', clickAddWebsite: 'Нажмите «Добавить сайт», чтобы начать.', noWebsitesMatch: 'Нет сайтов, соответствующих текущему поиску или фильтрам.',
    thWebsite: 'САЙТ', thUrlEndpoint: 'URL / ЭНДПОИНТ', thInterval: 'ИНТЕРВАЛ', thStatus: 'СТАТУС', thHealth: 'ЗДОРОВЬЕ', thLatency: 'ЗАДЕРЖКА', thHttp: 'HTTP', thSsl: 'SSL', thNetLatencies: 'СЕТЕВЫЕ ЗАДЕРЖКИ', thActions: 'ДЕЙСТВИЯ',
    editBtn: 'Правка', deleteBtn: 'Удалить', editWebsiteTitle: 'Изменить сайт', addWebsiteModalTitle: 'Добавить сайт', confirmDeleteTitle: 'Подтвердить удаление',
    fieldName: 'ИМЯ *', fieldNamePh: 'Мой сайт', fieldUrl: 'URL *', fieldDescription: 'ОПИСАНИЕ', fieldDescriptionPh: 'Необязательное описание', fieldInterval: 'ИНТЕРВАЛ МОНИТОРИНГА',
    interval30: '30 секунд (Быстро)', interval60: '60 секунд (Рекомендуется)', interval120: '120 секунд (Обычно)', secondsCurrent: 'секунд (Текущий)',
    takeScreenshot: 'ДЕЛАТЬ СКРИНШОТ СТРАНИЦЫ (СОХРАНИТЬ ФОТО)', saveBtn: 'Сохранить', failedToSave: 'Не удалось сохранить',
    deleteConfirmPrefix: 'Удалить', deleteConfirmSuffix: '? Это также навсегда удалит все журналы мониторинга из базы данных.',
    selectMode: 'Режим выбора', selectAllTitle: 'Выбрать все на этой странице', selectedSuffix: 'выбрано', clearSelectionBtn: 'Очистить', deleteSelectedBtn: 'Удалить выбранные', bulkDeleteTitle: 'Подтвердить массовое удаление', bulkDeleteUnit: 'выбранных сайтов',
    deleteAllBtn: 'Удалить все', bulkDeleteFailed: 'Не удалось удалить сайты. Попробуйте снова.', bulkDeleteAllWarning: 'Вы собираетесь безвозвратно удалить ВСЕ сайты вместе со всеми журналами мониторинга и историей. Это действие нельзя отменить.', bulkConfirmTypePrefix: 'Введите', bulkConfirmTypeSuffix: 'чтобы продолжить.', bulkDeleteAllKeyword: 'УДАЛИТЬ ВСЕ',
    exp: 'Истек', ipLabelShort: 'IP',
    activityLogTitle: 'Журнал активности', completeHistory: 'Полная история', eventsLabel: 'событий', noEventsFound: 'События не найдены.',
    colTransition: 'Переход', colNewStatus: 'Новый статус', colTime: 'Время',
    userManagement: 'Управление пользователями', usersLabel: 'пользователей', adminsUsed: 'админов использовано', createUserBtn: '+ СОЗДАТЬ ЮЗЕРА', adminSlots: 'СЛОТЫ АДМИНОВ',
    thUsername: 'ИМЯ ПОЛЬЗОВАТЕЛЯ', thRole: 'РОЛЬ', thCreatedAt: 'СОЗДАН', noUsersFound: 'Пользователи не найдены.', protectedLabel: 'Защищён', currentUserLabel: 'Текущий пользователь', youLabel: 'Вы',
    promoteBtn: '↑ Повысить', demoteBtn: '↓ Понизить', maxAdminsReached: 'Достигнут максимум 3 админа', promoteToAdmin: 'Повысить до Admin',
    deleteUserTitle: 'Удалить пользователя', deleteUserConfirmPrefix: 'Удалить', cannotBeUndone: '? Это нельзя отменить.', createNewUser: 'Создать пользователя',
    fieldPassword: 'ПАРОЛЬ', passwordMinPh: 'пароль (мин. 6 символов)', roleViewer: 'Viewer', roleAdmin: 'Admin', roleAdminPelindo: 'Admin Pelindo', fieldEmail: 'EMAIL *', fieldTelegramOpt: 'TELEGRAM ID (Необязательно)', createUserSubmit: 'Создать пользователя',
    refresh: 'ОБНОВИТЬ', refreshing: 'ОБНОВЛЕНИЕ...', connecting: 'ПОДКЛЮЧЕНИЕ', allMonitoredNodes: 'Все отслеживаемые узлы', searchNodeUrl: 'Поиск имени узла или URL...',
    thEndpointName: 'ИМЯ ЭНДПОИНТА', thUrl: 'URL', noWebsitesMonitored: 'Нет отслеживаемых сайтов', addWebsitesToBegin: 'Добавьте сайты, чтобы начать мониторинг',
    cpuUsage: 'ЗАГРУЗКА CPU', ramUsage: 'ЗАГРУЗКА RAM', networkConnection: 'СЕТЕВОЕ СОЕДИНЕНИЕ', netType: 'ТИП', netName: 'ИМЯ СЕТИ', endpointIpAddress: 'ЭНДПОИНТ И IP-АДРЕС', httpCodeLabel: 'КОД HTTP', sslStatusLabel: 'СТАТУС SSL', lastCheckLabel: 'ПОСЛЕД. ПРОВЕРКА', failedRecheck: 'Не удалось запустить повторную проверку',
    networkTopologyTitle: 'СЕТЕВАЯ ТОПОЛОГИЯ', nodesLabel: 'узлов', moreLabel: 'ЕЩЁ', listLabel: 'Список', mapLabel: 'Карта', showingAll: 'Показаны все', endpointsLabel: 'эндпоинтов', noNodesMatch: 'Нет узлов, соответствующих выбранному поиску или фильтрам.', highLoadClick: '⚠️ ВЫСОКАЯ НАГРУЗКА — нажмите для деталей',
    srvResourceUsage: 'ИСПОЛЬЗОВАНИЕ РЕСУРСОВ', srvWorkerRuntime: 'ВОРКЕРЫ И RUNTIME', srvNetworkInfo: 'СЕТЕВАЯ ИНФОРМАЦИЯ', srvAnalysis: 'АНАЛИЗ И РЕКОМЕНДАЦИИ', srvActiveWorkers: 'АКТИВНЫЕ ВОРКЕРЫ', srvQueueSize: 'РАЗМЕР ОЧЕРЕДИ', srvGoroutines: 'ГОРУТИНЫ', srvWsConn: 'WS СОЕДИНЕНИЯ', srvConnType: 'Тип соединения', srvNetName: 'Имя сети', srvInterface: 'Интерфейс', srvGateway: 'Шлюз', srvDnsResolver: 'DNS-резолвер', srvLinkSpeed: 'Скорость сети', srvDownload: 'Загрузка', srvUpload: 'Выгрузка', srvLoading: 'Загрузка данных сервера…', srvAutoRefresh: 'Автообновление каждые 4 секунды · нажмите Esc для закрытия', srvLocalSystem: 'Локальная система', srvUpdated: 'Обновлено', srvNormal: 'НОРМА', srvExceeds: 'Превышает порог',
    createAccount: 'Создать аккаунт', welcome: 'Добро пожаловать', signUpMonitor: 'Зарегистрируйтесь для мониторинга сервисов', signInAccess: 'Войдите, чтобы открыть панель мониторинга',
    usernamePh: 'Имя пользователя', emailReqPh: 'Email *', telegramOptPh: 'Telegram ID (необязательно)', passwordPh: 'Пароль', register: 'РЕГИСТРАЦИЯ', signIn: 'ВОЙТИ',
    alreadyHaveAccount: 'Уже есть аккаунт? ', needAccount: 'Нужен аккаунт? ', signInLink: 'Войти', registerHere: 'Зарегистрироваться', completeCaptcha: 'Пожалуйста, пройдите CAPTCHA', regSuccess: 'Регистрация успешна! Ваша учётная запись ожидает одобрения администратора перед входом.', rememberMe: 'Запомнить меня', telegramPhonePh: 'Телефон Telegram (напр. 0812xxxxxxx)', regFailed: 'Регистрация не удалась.', loginFailed: 'Не удалось войти. Проверьте учётные данные.', loginSuccess: 'Вход выполнен',
  }
}

// Maps a raw status code (ONLINE, OFFLINE, …) to its translated label.
// Status codes themselves stay as data; only the displayed text is localized.
const STATUS_KEY = { ONLINE: 'online', OFFLINE: 'offline', CRITICAL: 'critical', WARNING: 'warning', UNKNOWN: 'unknown', PENDING: 'pending' }

export const THEME_OPTIONS = [
  { id: 'theme-light', name: 'Light Mode', color: '#3b82f6', dark: false },
  { id: 'theme-dark', name: 'Dark Mode', color: '#00d1b2', dark: true }
]

export function ThemeProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('spmt_lang')
    return LANGUAGES[saved] ? saved : 'en'
  })
  const [themeId, setThemeId] = useState(() => {
    const saved = localStorage.getItem('spmt_theme')
    return saved === 'theme-light' || saved === 'theme-dark' ? saved : 'theme-light'
  })

  // The theme is now applied locally in App.jsx to prevent affecting Public/Login pages

  const setTheme = useCallback((id) => {
    setThemeId(id)
    localStorage.setItem('spmt_theme', id)
  }, [])

  const setLanguage = useCallback((code) => {
    if (!LANGUAGES[code]) return
    setLang(code)
    localStorage.setItem('spmt_lang', code)
  }, [])

  const t = TRANSLATIONS[lang] || TRANSLATIONS.en

  // Translate a raw status code to the active language (falls back to the code).
  const tStatus = useCallback((status) => {
    if (!status) return t.pending
    const key = STATUS_KEY[String(status).toUpperCase()]
    return key ? t[key] : status
  }, [t])

  return (
    <ThemeContext.Provider value={{
      lang, setLanguage, t, tStatus, LANGUAGES,
      themeId, setTheme, THEME_OPTIONS
    }}>
      {children}
    </ThemeContext.Provider>
  )
}

export const useTheme = () => useContext(ThemeContext)
